-- ============================================================
-- VOLLSTAENDIGES Postgres-Schema: ALLE 179 Tabellen aus dem
-- MySQL-Produktions-Dump vom 26.02.2026, konvertiert + verifiziert.
-- Zweck: kompletter Neon-Branch als ERSATZ fuer den alten MySQL-Server.
-- Foreign Keys bewusst weggelassen (Import-Reihenfolge egal).
-- ============================================================

CREATE TABLE IF NOT EXISTS "idk_agenti_activity" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_id" int NOT NULL,
  "activity_status" int DEFAULT '0',
  "activity_pocetak" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "activity_kraj" timestamp DEFAULT NULL,
  "activity_ukupno" time DEFAULT '00:00:00',
  "activity_aktivan" int NOT NULL DEFAULT '1',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_analitika" (
  "analizika_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "analitika_rating" int DEFAULT NULL,
  "analitika_datum" timestamp DEFAULT NULL,
  PRIMARY KEY (analizika_id)
);

CREATE TABLE IF NOT EXISTS "idk_api_clients" (
  "client_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_name" varchar(525) NOT NULL,
  "client_token" varchar(525) NOT NULL,
  PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS "idk_appointment_invite_links" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "candidate_id" int NOT NULL,
  "interview_id" int NOT NULL,
  "link_status" int NOT NULL,
  "date_sent" timestamp DEFAULT NULL,
  "date_open" timestamp DEFAULT NULL,
  "date_confirmed" timestamp DEFAULT NULL,
  "date_archived" timestamp DEFAULT NULL,
  "send_key" varchar(50) NOT NULL,
  "sent_days_before" int DEFAULT NULL,
  "counter_sent" int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "interview_id" ON "idk_appointment_invite_links" (interview_id);

CREATE TABLE IF NOT EXISTS "idk_bot_obavijesti" (
  "bo_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "bo_kandidat_id" int NOT NULL,
  "bo_nalog_id" int NOT NULL,
  "bo_poslana" int NOT NULL,
  "bo_odgovor" int DEFAULT '0',
  PRIMARY KEY (bo_id)
);

CREATE TABLE IF NOT EXISTS "idk_candidate_language_logs" (
  "cll_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cll_candidate_id" int NOT NULL,
  "cll_cvl_id" int NOT NULL,
  "cll_status" int NOT NULL,
  "cll_date" timestamp NOT NULL,
  "cll_employee_id" int NOT NULL,
  "cll_days_count" int DEFAULT NULL,
  PRIMARY KEY (cll_id)
);

CREATE TABLE IF NOT EXISTS "idk_candidate_verified_languages" (
  "cvl_id" int NOT NULL,
  "cvl_status" int NOT NULL,
  "cvl_active" int NOT NULL DEFAULT '0',
  "cvl_course1_started" date DEFAULT NULL,
  "cvl_course1_ended" date DEFAULT NULL,
  "cvl_course2_started" date DEFAULT NULL,
  "cvl_course2_ended" date DEFAULT NULL,
  "cvl_motive_start" date DEFAULT NULL,
  "cvl_motive_end" date DEFAULT NULL,
  "cvl_exam_date" date DEFAULT NULL,
  "cvl_certificate_path" text,
  "cvl_certificate_upload_date" timestamp DEFAULT NULL,
  "cvl_certficate_creation_date" date DEFAULT NULL,
  "cvl_certificate_expiration_date" date DEFAULT NULL,
  "cvl_last_updated" timestamp DEFAULT NULL,
  PRIMARY KEY (cvl_id)
);
CREATE INDEX IF NOT EXISTS "cvl_active" ON "idk_candidate_verified_languages" (cvl_active);

CREATE TABLE IF NOT EXISTS "idk_chat_question" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type" text NOT NULL,
  "question_order" int DEFAULT NULL,
  "question" text NOT NULL,
  "answer" text,
  "parentQuestion" int DEFAULT NULL,
  "deletedAt" timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_chat_type" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(150) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_clients" (
  "client_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_name" varchar(250) DEFAULT NULL,
  "client_country" varchar(255) DEFAULT NULL,
  "client_region" varchar(100) DEFAULT NULL,
  "client_city" varchar(250) DEFAULT NULL,
  "client_address" varchar(250) DEFAULT NULL,
  "client_pp" int DEFAULT NULL,
  "client_telephone" varchar(250) DEFAULT NULL,
  "client_email" varchar(250) DEFAULT NULL,
  "client_origin" int NOT NULL,
  "client_recommendation" int DEFAULT NULL,
  "client_recommendation_company" int DEFAULT NULL,
  "client_fc_or_sales" int NOT NULL,
  "client_fc_status" int NOT NULL,
  "client_sales_status" int NOT NULL,
  "client_manager" int DEFAULT NULL,
  "client_sales_manager" int DEFAULT NULL,
  "client_datum_zvanja" date DEFAULT NULL,
  "client_contract" int NOT NULL DEFAULT '0',
  "client_description" text,
  PRIMARY KEY (client_id)
);

CREATE TABLE IF NOT EXISTS "idk_clients_stats" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "client_id" int DEFAULT NULL,
  "status" int DEFAULT NULL,
  "fc_or_sales" int DEFAULT NULL,
  "date" timestamp DEFAULT NULL,
  "zaposlenik_id" int DEFAULT NULL,
  "stats_desc" text,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_companies" (
  "company_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "company_name" varchar(150) NOT NULL,
  "company_type" varchar(50) DEFAULT NULL,
  "company_idnum" varchar(50) DEFAULT NULL,
  "company_taxnum" varchar(50) DEFAULT NULL,
  "company_ceo" int DEFAULT NULL,
  "company_contact" int DEFAULT NULL,
  "company_address" varchar(250) DEFAULT NULL,
  "company_zipcode" varchar(50) DEFAULT NULL,
  "company_city" varchar(150) DEFAULT NULL,
  "company_state" varchar(150) DEFAULT NULL,
  "company_country" varchar(150) DEFAULT NULL,
  "company_info" text,
  "company_inote" text,
  "company_logo" varchar(50) DEFAULT NULL,
  "company_contact_type" varchar(150) DEFAULT NULL,
  "company_datetime" timestamp NOT NULL,
  "company_status" int DEFAULT NULL,
  "company_origin" int NOT NULL DEFAULT '0',
  "company_reccomendation" int DEFAULT NULL,
  "company_size" varchar(255) DEFAULT NULL,
  "js_partner_id" int DEFAULT NULL,
  "company_message" text,
  "company_total_workers_required" int DEFAULT NULL,
  "company_professions" text,
  PRIMARY KEY (company_id)
);

CREATE TABLE IF NOT EXISTS "idk_companies_info" (
  "comi_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "comi_group" int NOT NULL,
  "comi_title" varchar(150) NOT NULL,
  "comi_data" varchar(250) NOT NULL,
  "comi_primary" int NOT NULL,
  "comi_companyid" int NOT NULL,
  PRIMARY KEY (comi_id)
);
CREATE INDEX IF NOT EXISTS "comi_companyid" ON "idk_companies_info" (comi_companyid);

CREATE TABLE IF NOT EXISTS "idk_contacts" (
  "contact_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "contact_firstname" varchar(150) NOT NULL,
  "contact_lastname" varchar(150) DEFAULT NULL,
  "contact_nickname" varchar(150) DEFAULT NULL,
  "contact_dob" date DEFAULT NULL,
  "contact_address" varchar(250) DEFAULT NULL,
  "contact_zipcode" int DEFAULT NULL,
  "contact_city" varchar(150) DEFAULT NULL,
  "contact_state" varchar(150) DEFAULT NULL,
  "contact_country" varchar(150) DEFAULT NULL,
  "contact_info" text,
  "contact_inote" text,
  "contact_image" varchar(250) DEFAULT NULL,
  "contact_type" varchar(50) DEFAULT NULL,
  "contact_companyid" int NOT NULL DEFAULT '0',
  "contact_clientid" int DEFAULT NULL,
  "contact_ownerid" int DEFAULT NULL,
  "contact_datetime" timestamp NOT NULL,
  "contact_status" int NOT NULL,
  "contact_job_title" varchar(255) DEFAULT NULL,
  PRIMARY KEY (contact_id)
);

CREATE TABLE IF NOT EXISTS "idk_contacts_info" (
  "ci_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ci_group" int NOT NULL,
  "ci_title" varchar(150) NOT NULL,
  "ci_data" varchar(250) NOT NULL,
  "ci_primary" int NOT NULL,
  "ci_contactid" int NOT NULL,
  PRIMARY KEY (ci_id)
);

CREATE TABLE IF NOT EXISTS "idk_dak_kandidati" (
  "id_dak_kandidat" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "origin_dak_kandidat" int DEFAULT NULL,
  "tel_dak_kandidat" varchar(250) DEFAULT NULL,
  "hashedtel_idk_dak_kandidat" text,
  "telconfirm_dak_kandidat" varchar(250) DEFAULT NULL,
  "pin_dak_kandidat" text,
  "name_dak_kandidat" varchar(250) DEFAULT NULL,
  "lastname_dak_kandidat" varchar(250) DEFAULT NULL,
  "email_dak_kandidat" varchar(250) DEFAULT NULL,
  "contacttime_dak_kandidat" timestamp DEFAULT NULL,
  "daypart_dak_kandidat" int DEFAULT NULL,
  "comment_dak_kandidat" text,
  "passport_dak_kandidat" varchar(250) DEFAULT NULL,
  "passporttime_dak_kandidat" timestamp DEFAULT NULL,
  "contract_dak_kandidat" varchar(250) DEFAULT NULL,
  "contracttime_dak_kandidat" timestamp DEFAULT NULL,
  "status_dak_kandidat" int DEFAULT NULL,
  "tipunosa_dak_kandidat" int DEFAULT NULL,
  "datumunosa_dak_kandidat" timestamp DEFAULT NULL,
  "datumobrade_dak_kandidat" timestamp DEFAULT NULL,
  "datumslanja_dak_kandidat" timestamp DEFAULT NULL,
  "pocetakrada_dak_kandidat" date DEFAULT NULL,
  "datumaktivacije_dak_kandidat" timestamp DEFAULT NULL,
  "datumzavrsetka_dak_kandidat" timestamp DEFAULT NULL,
  "datumstornoaktivacije_dak_kandidat" timestamp DEFAULT NULL,
  "datumstornacije_dak_kandidat" timestamp DEFAULT NULL,
  "company_dak_kandidat" int DEFAULT NULL,
  "nas_klijent_dak_kandidat" int DEFAULT NULL,
  "dipl_dak_kandidat" int NOT NULL DEFAULT '0',
  "osiguranje_dak_kandidat" int NOT NULL DEFAULT '0',
  "poslovnica_dak_kandidat" int NOT NULL DEFAULT '0',
  "rata1_dak_kandidat" int NOT NULL DEFAULT '0',
  "rata1_datum_dak_kandidat" timestamp DEFAULT NULL,
  "rata2_dak_kandidat" int NOT NULL DEFAULT '0',
  "rata2_datum_dak_kandidat" timestamp DEFAULT NULL,
  "manager_dak_kandidat" int DEFAULT NULL,
  PRIMARY KEY (id_dak_kandidat)
);

CREATE TABLE IF NOT EXISTS "idk_documents" (
  "document_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "document_name" varchar(150) NOT NULL,
  "document_special_type" int DEFAULT NULL,
  "document_desc" varchar(250) NOT NULL,
  "document_file" varchar(150) NOT NULL,
  "document_icon" varchar(5) NOT NULL,
  "document_datetime" timestamp NOT NULL,
  "document_group" int NOT NULL,
  "document_dataid" int NOT NULL,
  "document_employeeid" int NOT NULL,
  PRIMARY KEY (document_id)
);

CREATE TABLE IF NOT EXISTS "idk_duration_per_status" (
  "dpr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "dpr_group" int NOT NULL,
  "dpr_status" varchar(10) NOT NULL,
  "dpr_duration" int NOT NULL,
  "dpr_description" varchar(400) NOT NULL,
  "dpr_status_name" varchar(100) NOT NULL,
  PRIMARY KEY (dpr_id)
);

CREATE TABLE IF NOT EXISTS "idk_email_text" (
  "email_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email_value" varchar(100) NOT NULL,
  "email_title" varchar(255) NOT NULL,
  "email_txt" text NOT NULL,
  PRIMARY KEY (email_id)
);

CREATE TABLE IF NOT EXISTS "idk_employees" (
  "employee_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_firstname" varchar(150) NOT NULL,
  "employee_lastname" varchar(150) NOT NULL,
  "employee_email" varchar(250) NOT NULL,
  "employee_password" varchar(250) NOT NULL,
  "employee_key" varchar(150) NOT NULL,
  "employee_color" varchar(10) DEFAULT NULL,
  "employee_jmbg" bigint DEFAULT NULL,
  "employee_rfid" varchar(50) NOT NULL,
  "employee_position" varchar(150) NOT NULL,
  "employee_dob" date DEFAULT NULL,
  "employee_doe" date DEFAULT NULL,
  "employee_address" text NOT NULL,
  "employee_city" varchar(150) NOT NULL,
  "employee_country" varchar(150) NOT NULL,
  "employee_info" text NOT NULL,
  "employee_inote" text NOT NULL,
  "employee_image" varchar(150) NOT NULL,
  "employee_status" varchar(255) NOT NULL,
  "employee_supervizor" varchar(255) DEFAULT NULL,
  "employee_dlanguage" varchar(50) NOT NULL DEFAULT 'bs',
  "employee_phone" varchar(250) DEFAULT NULL,
  "employee_warehouse" int NOT NULL DEFAULT '0',
  "employee_odjel" int NOT NULL DEFAULT '0',
  "employee_poslovnica" int DEFAULT NULL,
  "employee_nostrifikacija_diploma" int DEFAULT NULL,
  "employee_nostrifikacija_zadnji_menadzer" int DEFAULT NULL,
  "employee_nostrifikacija_zadnji_menadzer_app" int DEFAULT NULL,
  "employee_faktor_provizije_bih" double precision NOT NULL DEFAULT '0',
  "employee_faktor_provizije_srb" double precision NOT NULL DEFAULT '0',
  "employee_faktor_za_timove" double precision NOT NULL DEFAULT '0',
  "employee_team" int NOT NULL DEFAULT '1',
  "employee_viciuser" varchar(150) DEFAULT NULL,
  "employee_vicipass" varchar(150) DEFAULT NULL,
  "employee_reset_password" int NOT NULL DEFAULT '0',
  "employee_last_password_change" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "employee_reset_token" varchar(255) DEFAULT NULL,
  "employee_reset_token_doe" timestamp DEFAULT NULL,
  "employee_dvag" int NOT NULL DEFAULT '0',
  "employee_makler_representative_status" int NOT NULL DEFAULT '0',
  PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS "idk_employees_info" (
  "ei_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ei_group" int NOT NULL,
  "ei_title" varchar(150) NOT NULL,
  "ei_data" varchar(250) NOT NULL,
  "ei_primary" int NOT NULL,
  "ei_employeeid" int NOT NULL,
  PRIMARY KEY (ei_id)
);

CREATE TABLE IF NOT EXISTS "idk_employees_reports" (
  "er_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "er_date" date NOT NULL,
  "er_title" varchar(250) DEFAULT NULL,
  "er_timefrom" time DEFAULT NULL,
  "er_timeto" time DEFAULT NULL,
  "er_projectid" int DEFAULT '0',
  "er_nalogid" int DEFAULT NULL,
  "er_employeeid" int NOT NULL,
  "er_status" int NOT NULL,
  PRIMARY KEY (er_id)
);

CREATE TABLE IF NOT EXISTS "idk_glossa_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "request" text NOT NULL,
  "response" text NOT NULL,
  "code" int NOT NULL,
  "candidate" text NOT NULL,
  "request_endpoint" varchar(255) NOT NULL,
  "doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_ipwhitelist" (
  "ipwl_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ipwl_user" varchar(255) NOT NULL,
  "ipwl_ip" varchar(100) NOT NULL,
  "ipwl_added_by" varchar(100) NOT NULL,
  "ipwl_reason" varchar(250) NOT NULL,
  "ipwl_status" int NOT NULL DEFAULT '0',
  "ipwl_datetime" timestamp NOT NULL,
  PRIMARY KEY (ipwl_id)
);

CREATE TABLE IF NOT EXISTS "idk_jobstep_partners" (
  "jp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jp_imeprezime" varchar(255) NOT NULL,
  "jp_ime" varchar(255) DEFAULT NULL,
  "jp_prezime" varchar(255) DEFAULT NULL,
  "jp_email" varchar(255) NOT NULL,
  "jp_password" varchar(255) NOT NULL,
  "jp_lang" varchar(255) DEFAULT NULL,
  "jp_posta" int DEFAULT NULL,
  "jp_racun" int DEFAULT NULL,
  "jp_iban" varchar(255) DEFAULT NULL,
  "jp_swift" varchar(255) DEFAULT NULL,
  "jp_placanjeimeprezime" varchar(255) DEFAULT NULL,
  "jp_brtelefona" varchar(255) DEFAULT NULL,
  "jp_drzava" varchar(255) DEFAULT NULL,
  "jp_grad" varchar(255) DEFAULT NULL,
  "jp_postanskibroj" int DEFAULT NULL,
  "jp_ulica" varchar(255) DEFAULT NULL,
  "jp_provider" varchar(255) DEFAULT NULL,
  "jp_register_date" timestamp NOT NULL,
  "jp_fcmtoken" varchar(550) DEFAULT NULL,
  "jp_mailconfirmation_token" varchar(255) NOT NULL,
  "jp_confirmedaccount" int NOT NULL DEFAULT '0',
  "jp_position" int DEFAULT '1',
  "jp_socialid" text,
  "jp_social_token" text,
  "jp_social_imgurl" text,
  "jp_preporuka_id" int DEFAULT NULL,
  "jp_source" int NOT NULL DEFAULT '0',
  "jp_user_type" int DEFAULT '0',
  "jp_user_permission" int DEFAULT NULL,
  "jp_partner_company" int NOT NULL,
  "jp_makler_id" varchar(255) DEFAULT NULL,
  "jp_direction_number" varchar(255) DEFAULT NULL,
  "jp_region_de" varchar(255) DEFAULT NULL,
  "jp_spoken_languages" text,
  "jp_received_last_lead" int DEFAULT NULL,
  "jp_last_password_reset" timestamp NULL DEFAULT NULL,
  "jp_makler_broj_direkcije" varchar(10) DEFAULT NULL,
  "jp_representative_employee_id" int DEFAULT NULL,
  "jp_latest_login" timestamp DEFAULT NULL,
  "jp_first_login" timestamp DEFAULT NULL,
  "jp_datum_deaktivacije" timestamp DEFAULT NULL,
  "jp_latest_activity" timestamp DEFAULT NULL,
  "jp_tutorial_sent" varchar(200) DEFAULT NULL,
  "jp_password_reset_code" varchar(255) DEFAULT NULL,
  "jp_password_reset_datetime" timestamp NULL DEFAULT NULL,
  "jp_password_reset_tries" int DEFAULT NULL,
  "jp_device" varchar(255) DEFAULT NULL,
  "jp_app_version" varchar(255) DEFAULT NULL,
  PRIMARY KEY (jp_id)
);

CREATE TABLE IF NOT EXISTS "idk_jobstep_partners_pregledi" (
  "jpp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jpp_partnerid" varchar(255) NOT NULL,
  "jpp_nalogid" int NOT NULL,
  "jpp_pregledi_count" int NOT NULL DEFAULT '0',
  PRIMARY KEY (jpp_id)
);

CREATE TABLE IF NOT EXISTS "idk_kampanje_dipl" (
  "kd_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kd_naziv" varchar(255) NOT NULL,
  "kd_skraceni_naziv" varchar(255) DEFAULT NULL,
  "kd_poruka_kampanje" text,
  "kd_jezik_forme" varchar(10) NOT NULL,
  "kd_drzava" varchar(10) NOT NULL,
  "kd_broj_pregleda" int NOT NULL DEFAULT '0',
  "kd_broj_prijavljenih" int NOT NULL DEFAULT '0',
  "kd_datum_kreiranja" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "kd_troskovi" double precision DEFAULT NULL,
  "kd_status" int NOT NULL DEFAULT '1',
  "kd_slike" text,
  "kd_category" varchar(3) NOT NULL DEFAULT 'C',
  PRIMARY KEY (kd_id)
);
CREATE INDEX IF NOT EXISTS "kd_drzava" ON "idk_kampanje_dipl" (kd_drzava);

CREATE TABLE IF NOT EXISTS "idk_kandidat_akademija" (
  "ka_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ka_kandidat_id" int NOT NULL,
  "ka_nalog_id" int NOT NULL,
  "ka_status" int NOT NULL,
  "ka_date_from" date NOT NULL,
  "ka_date_to" date NOT NULL,
  "ka_note" text,
  "ka_rating" int DEFAULT NULL,
  PRIMARY KEY (ka_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_cv" (
  "kcv_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kcv_kandidatid" int DEFAULT NULL,
  "kcv_ba" varchar(255) DEFAULT NULL,
  "kcv_de" varchar(255) DEFAULT NULL,
  PRIMARY KEY (kcv_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_de" (
  "kde_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kde_kandidat_id" int DEFAULT NULL,
  "kde_prijava_na" varchar(400) DEFAULT NULL,
  "kde_spol" varchar(255) DEFAULT NULL,
  "kde_drzavljanstvo" varchar(255) DEFAULT NULL,
  "kde_vozacka" varchar(100) DEFAULT NULL,
  PRIMARY KEY (kde_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_edukacija" (
  "ke_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ke_orderid" int NOT NULL DEFAULT '0',
  "ke_datumod" date DEFAULT NULL,
  "ke_datumdo" date DEFAULT NULL,
  "ke_aktuelno" int NOT NULL DEFAULT '0',
  "ke_smjer_id" int DEFAULT NULL,
  "ke_naziv_kvalifikacije" varchar(100) NOT NULL,
  "ke_naziv_kvalifikacije_de" varchar(100) DEFAULT NULL,
  "ke_skola_id" int DEFAULT NULL,
  "ke_naziv" varchar(100) DEFAULT NULL,
  "ke_naziv_de" varchar(250) DEFAULT NULL,
  "ke_grad" varchar(50) DEFAULT NULL,
  "ke_grad_de" varchar(200) DEFAULT NULL,
  "ke_drzava" varchar(100) DEFAULT NULL,
  "ke_opis" text,
  "ke_opis_de" text,
  "ke_kandidat_id" int NOT NULL,
  "ke_vrsta_obrazovanja" varchar(50) DEFAULT NULL,
  "ke_prikaz_pp" int NOT NULL DEFAULT '0',
  PRIMARY KEY (ke_id)
);
CREATE INDEX IF NOT EXISTS "ke_id" ON "idk_kandidat_edukacija" (ke_id);
CREATE INDEX IF NOT EXISTS "ke_kandidat_id" ON "idk_kandidat_edukacija" (ke_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_financije" (
  "kf_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nalog_id" int NOT NULL,
  "projekt_id" int DEFAULT NULL,
  "kandidat_id" int NOT NULL,
  "kf_datum" date NOT NULL,
  "kf_datum_stvarni" date NOT NULL,
  "kf_nalog_rata_id" int DEFAULT NULL,
  "kf_type" int NOT NULL,
  "kf_iznos" double precision NOT NULL,
  "kf_placeno" int DEFAULT '0',
  "kf_datum_fakturisanja" date DEFAULT NULL,
  "kf_datum_placanja" date DEFAULT NULL,
  "kf_status" int DEFAULT '1',
  "kf_zamjena_id" int DEFAULT NULL,
  PRIMARY KEY (kf_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_jezici" (
  "kj_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kj_naziv" varchar(150) NOT NULL,
  "kj_naziv_de" varchar(255) DEFAULT NULL,
  "kj_slusanje" varchar(50) NOT NULL,
  "kj_slusanje_de" varchar(255) DEFAULT NULL,
  "kj_citanje" varchar(50) NOT NULL,
  "kj_citanje_de" varchar(255) DEFAULT NULL,
  "kj_govorna_interakcija" varchar(50) NOT NULL,
  "kj_govorna_interakcija_de" varchar(255) DEFAULT NULL,
  "kj_govorna_produkcija" varchar(50) NOT NULL,
  "kj_govorna_produkcija_de" varchar(255) DEFAULT NULL,
  "kj_pisanje" varchar(50) NOT NULL,
  "kj_pisanje_de" varchar(255) DEFAULT NULL,
  "kj_kandidatid" int NOT NULL,
  "kj_ustanova" int DEFAULT NULL,
  PRIMARY KEY (kj_id)
);
CREATE INDEX IF NOT EXISTS "kj_naziv" ON "idk_kandidat_jezici" (kj_naziv);
CREATE INDEX IF NOT EXISTS "kj_kandidatid" ON "idk_kandidat_jezici" (kj_kandidatid);
CREATE INDEX IF NOT EXISTS "kj_slusanje" ON "idk_kandidat_jezici" (kj_slusanje);

CREATE TABLE IF NOT EXISTS "idk_kandidat_kontakt_info" (
  "kki_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kki_orderid" int DEFAULT '0',
  "kki_grupa" int NOT NULL,
  "kki_naziv" varchar(100) NOT NULL,
  "kki_naziv_de" varchar(255) DEFAULT NULL,
  "kki_podatak" varchar(100) DEFAULT NULL,
  "kki_kandidat_id" int NOT NULL,
  "kki_primary" int NOT NULL DEFAULT '1',
  PRIMARY KEY (kki_id)
);
CREATE INDEX IF NOT EXISTS "kki_id" ON "idk_kandidat_kontakt_info" (kki_id);
CREATE INDEX IF NOT EXISTS "kki_kandidat_id" ON "idk_kandidat_kontakt_info" (kki_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_pozicija" (
  "kp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kp_ime" varchar(150) DEFAULT NULL,
  "kp_ime_de" varchar(150) DEFAULT NULL,
  "kp_ime_en" varchar(150) DEFAULT NULL,
  "kp_ime_rs" varchar(150) DEFAULT NULL,
  "kp_opis" text,
  "kp_created_by" int DEFAULT NULL,
  "kp_source" int NOT NULL DEFAULT '1',
  "kp_active" int NOT NULL DEFAULT '1',
  PRIMARY KEY (kp_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_projekcije" (
  "kandidat_id" int NOT NULL,
  "proracunati_pocetak_rada" date NOT NULL,
  PRIMARY KEY (kandidat_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_radno_iskustvo" (
  "kri_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kri_order" int DEFAULT '0',
  "kri_darum_od" date NOT NULL,
  "kri_datum_do" date DEFAULT NULL,
  "kri_aktuelno" int NOT NULL DEFAULT '0',
  "kri_pozicija" varchar(250) NOT NULL,
  "kri_pozicija_de" varchar(400) DEFAULT NULL,
  "kri_pozicija_en" varchar(400) DEFAULT NULL,
  "kri_naziv" varchar(100) NOT NULL,
  "kri_naziv_de" varchar(250) DEFAULT NULL,
  "kri_grad" varchar(100) DEFAULT NULL,
  "kri_grad_de" varchar(200) DEFAULT NULL,
  "kri_drzava" varchar(100) DEFAULT NULL,
  "kri_adresa" varchar(100) DEFAULT NULL,
  "kri_telefon" varchar(50) DEFAULT NULL,
  "kri_email" varchar(50) DEFAULT NULL,
  "kri_web" varchar(50) DEFAULT NULL,
  "kri_opis" text,
  "kri_opis_de" text,
  "kri_kandidat_id" int NOT NULL,
  "kri_prikaz_pp" int NOT NULL DEFAULT '0',
  PRIMARY KEY (kri_id)
);
CREATE INDEX IF NOT EXISTS "kri_id" ON "idk_kandidat_radno_iskustvo" (kri_id);
CREATE INDEX IF NOT EXISTS "kri_kandidat_id" ON "idk_kandidat_radno_iskustvo" (kri_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_status" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_id" int DEFAULT NULL,
  "status_naziv" varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "status_id" ON "idk_kandidat_status" (status_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_status_prijave" (
  "status_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_naziv" varchar(100) NOT NULL,
  "status_aktivan" int NOT NULL DEFAULT '0',
  "rezervisanje" int NOT NULL DEFAULT '0',
  "redoslijed_statusa" int DEFAULT NULL,
  PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_vjestine" (
  "kv_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kv_naziv" varchar(150) NOT NULL,
  "kv_naziv_de" text,
  "kv_grupa" int NOT NULL,
  "kv_opis" text NOT NULL,
  "kv_opis_de" text,
  "kv_kandidat_id" int NOT NULL,
  PRIMARY KEY (kv_id)
);
CREATE INDEX IF NOT EXISTS "kv_id" ON "idk_kandidat_vjestine" (kv_id);

CREATE TABLE IF NOT EXISTS "idk_kandidati" (
  "kandidat_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kandidat_check" varchar(200) NOT NULL,
  "kandidat_ime" varchar(150) NOT NULL,
  "kandidat_prezime" varchar(150) NOT NULL,
  "kandidat_prijava_na" varchar(250) NOT NULL,
  "kandidat_spol" varchar(10) DEFAULT NULL,
  "kandidat_djevojackoprezime" varchar(150) DEFAULT NULL,
  "kandidat_jmbg" varchar(20) DEFAULT NULL,
  "kandidat_brojlk" varchar(50) DEFAULT NULL,
  "kandidat_broj_pasosa" varchar(50) DEFAULT NULL,
  "kandidat_datumrodjenja" date DEFAULT NULL,
  "kandidat_mjestorodjenja" varchar(150) DEFAULT NULL,
  "kandidat_drzavljanstvo_vrsta" varchar(100) DEFAULT NULL,
  "kandidat_drzavarodjenja" varchar(150) DEFAULT NULL,
  "kandidat_drzavljanstvo" varchar(150) DEFAULT NULL,
  "kandidat_bracnostanje" varchar(50) DEFAULT NULL,
  "kandidat_bracnostanjeod" date DEFAULT NULL,
  "kandidat_adresa" text,
  "kandidat_grad" varchar(150) DEFAULT NULL,
  "kandidat_pbroj" int DEFAULT NULL,
  "kandidat_drzava" varchar(150) DEFAULT NULL,
  "kandidat_email" varchar(250) DEFAULT NULL,
  "kandidat_mobitel" varchar(100) DEFAULT NULL,
  "kandidat_vozacka_dozvola" varchar(20) DEFAULT NULL,
  "kandidat_vozacka_kategorija" varchar(25) DEFAULT NULL,
  "kandidat_korisnickoime" varchar(250) DEFAULT NULL,
  "kandidat_password" varchar(150) DEFAULT NULL,
  "kandidat_slika" varchar(150) NOT NULL,
  "kandidat_status" int NOT NULL,
  "kandidat_status_messenger" int NOT NULL DEFAULT '0',
  "kandidat_datetime" timestamp NOT NULL,
  "kandidat_visitedurl" int DEFAULT '0',
  "kandidat_group" int NOT NULL DEFAULT '1',
  "kandidat_mailsent" int NOT NULL DEFAULT '0',
  "datum_termina" date DEFAULT NULL,
  "kandidat_bio_na_terminu" int DEFAULT NULL,
  "datum_aplikacije" date DEFAULT NULL,
  "kandidat_procjenatermina" int DEFAULT '0',
  "kandidat_viza" int DEFAULT NULL,
  "kandidat_viza_vrijedi_od" date DEFAULT NULL,
  "kandidat_viza_vrijedi_do" date DEFAULT NULL,
  "boravak_eu" varchar(255) DEFAULT NULL,
  "kandidat_status_prijave" int DEFAULT NULL,
  "kandidat_zaposlen_kod" int DEFAULT NULL,
  "cv_ba" int DEFAULT '0',
  "cv_de" int DEFAULT '0',
  "profile_ba" int NOT NULL DEFAULT '0',
  "profile_de" int NOT NULL DEFAULT '0',
  "kandidat_datum_ugovora" date DEFAULT NULL,
  "kandidat_datum_ugovora_mjesec" date DEFAULT NULL,
  "kandidat_datum_pocetakrada" date DEFAULT NULL,
  "kandidat_datum_pocetakrada_mjesec" date DEFAULT NULL,
  "kandidat_potencijalni_pocetak_rada" varchar(100) DEFAULT NULL,
  "kandidat_dogovoreni_pocetak_rada" date DEFAULT NULL,
  "kandidat_potvrden_pocetak_rada" int DEFAULT NULL,
  "kandidat_partnerid" int DEFAULT NULL,
  "kandidat_partner_status" int DEFAULT NULL,
  "kandidat_poslan_sms" varchar(255) DEFAULT NULL,
  "kandidat_sms_id" varchar(255) DEFAULT NULL,
  "kandidat_pogledao_link_prijave" int NOT NULL DEFAULT '0',
  "kandidat_poslan_dipl" int NOT NULL DEFAULT '0',
  "povezan_na_dipl" int NOT NULL DEFAULT '0',
  "kandidat_porijeklo" int NOT NULL DEFAULT '0',
  "struka_sa_prijave" int DEFAULT NULL,
  "kandidat_nalog_id" int DEFAULT NULL,
  "kandidat_latest_reserved_time" timestamp DEFAULT NULL,
  "kandidat_ppa_partner_id" int DEFAULT NULL,
  "kandidat_pp_lokacija" varchar(400) DEFAULT NULL,
  "kandidat_pp_pozicija" varchar(400) DEFAULT NULL,
  "kandidat_pp_plata" varchar(40) DEFAULT NULL,
  "kandidat_pp_povezao_user_id" int DEFAULT NULL,
  "kandidat_pp_razlog_odbijanja" varchar(255) DEFAULT NULL,
  "kandidat_pp_datum_prihvatanja" date DEFAULT NULL,
  "kandidat_dipl_id" int NOT NULL DEFAULT '0',
  "kandidat_ima_nostrifikaciju" int DEFAULT NULL,
  "kandidat_glossa" int NOT NULL DEFAULT '0',
  "kandidat_tf_status" int DEFAULT NULL,
  "kandidat_iskustvo_u_struci" int DEFAULT NULL,
  "kandidat_iskustvo_u_struci_trajanje" int DEFAULT NULL,
  "kandidat_termin_za_vizu" int DEFAULT NULL,
  "tf_reserved_agent" int DEFAULT NULL,
  "kandidat_nacin_odlaska" int NOT NULL DEFAULT '0',
  "kandidat_bracno_stanje" int NOT NULL DEFAULT '0',
  "kandidat_dostavljen_ugovor_jobstepu" int DEFAULT NULL,
  "kandidat_zeljena_regija" int DEFAULT NULL,
  "kandidat_zeljeni_grad" int DEFAULT NULL,
  "kandidat_partner_lead_status" int DEFAULT NULL,
  "zaduzeni_makler_id" int DEFAULT NULL,
  "zaduzen_makleru_datum" timestamp DEFAULT NULL,
  "zaduzeni_makler_reminder_datum" date DEFAULT NULL,
  "kandidat_nivo_obrazovanja" int DEFAULT NULL,
  "kandidat_partner_lead_biljeska" text,
  "kandidat_destinacija_grad" varchar(255) DEFAULT NULL,
  "kandidat_destinacija_postanski_broj" varchar(10) DEFAULT NULL,
  "assigned_to_makler" int DEFAULT NULL,
  "kandidat_paralelno_zb" int NOT NULL DEFAULT '0',
  "kandidat_pogresan_broj" int NOT NULL DEFAULT '0',
  "kandidat_nedostupan" int NOT NULL DEFAULT '0',
  "kandidat_atu_paket" int DEFAULT NULL,
  PRIMARY KEY (kandidat_id)
);
CREATE INDEX IF NOT EXISTS "kandidat_visitedurl" ON "idk_kandidati" (kandidat_visitedurl);
CREATE INDEX IF NOT EXISTS "kandidat_group" ON "idk_kandidati" (kandidat_group);
CREATE INDEX IF NOT EXISTS "kandidat_status" ON "idk_kandidati" (kandidat_status);
CREATE INDEX IF NOT EXISTS "kandidat_dipl_id" ON "idk_kandidati" (kandidat_dipl_id);
CREATE INDEX IF NOT EXISTS "kandidat_nalog_id" ON "idk_kandidati" (kandidat_nalog_id);
CREATE INDEX IF NOT EXISTS "tf_reserved_agent" ON "idk_kandidati" (tf_reserved_agent);
CREATE INDEX IF NOT EXISTS "kandidat_tf_status" ON "idk_kandidati" (kandidat_tf_status);
CREATE INDEX IF NOT EXISTS "kandidat_status_prijave" ON "idk_kandidati" (kandidat_status_prijave);

CREATE TABLE IF NOT EXISTS "idk_kandidati_contracts" (
  "kc_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kc_file_name" varchar(100) DEFAULT NULL,
  "kc_candidate_id" int NOT NULL,
  "kc_source" int NOT NULL,
  "kc_user_id" int NOT NULL,
  "kc_upload_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "kc_nalog_id" int NOT NULL,
  "kc_partner_id" int DEFAULT NULL,
  "kc_signed" int NOT NULL,
  "kc_visibility_status" int NOT NULL,
  PRIMARY KEY (kc_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidati_grupe" (
  "kg_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kg_title" varchar(255) NOT NULL,
  "kg_title_de" varchar(255) DEFAULT NULL,
  "kg_title_it" varchar(255) DEFAULT NULL,
  "kg_date" timestamp NOT NULL,
  "kg_employeeid" int NOT NULL,
  "kg_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (kg_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidati_reject_reasons" (
  "krr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "krr_reason_id" int NOT NULL,
  "krr_candidate_id" int NOT NULL,
  "krr_nalog_id" int NOT NULL,
  "krr_partner_id" int DEFAULT NULL,
  "krr_apointment_id" int DEFAULT NULL,
  "krr_description" text,
  "krr_source" int NOT NULL,
  "krr_done_by" int NOT NULL,
  "krr_date" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "krr_last_status" int NOT NULL,
  PRIMARY KEY (krr_id)
);

CREATE TABLE IF NOT EXISTS "idk_kategorije" (
  "kategorija_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kategorija_naziv" text,
  PRIMARY KEY (kategorija_id)
);

CREATE TABLE IF NOT EXISTS "idk_kategorije_provizija" (
  "kp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kp_naziv" varchar(100) NOT NULL,
  "kp_iznos" double precision NOT NULL DEFAULT '0',
  "kp_iznos_rs" double precision NOT NULL DEFAULT '0',
  "kp_faktorizacija" int NOT NULL DEFAULT '0',
  "kp_tip_id" int NOT NULL,
  "kp_status" int NOT NULL DEFAULT '1',
  "kp_odjeli" text,
  "kp_vrsta" int NOT NULL,
  "kp_employee_id" int DEFAULT NULL,
  PRIMARY KEY (kp_id)
);

CREATE TABLE IF NOT EXISTS "idk_korisni_dokumenti" (
  "kd_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kd_naziv" varchar(150) NOT NULL,
  "kd_detaljni_opis" text,
  "kd_file" varchar(150) NOT NULL,
  "kd_icon" varchar(5) NOT NULL,
  "kd_datetime" timestamp NOT NULL,
  "kd_employee_id" int NOT NULL,
  "kd_status" int NOT NULL DEFAULT '0',
  PRIMARY KEY (kd_id)
);

CREATE TABLE IF NOT EXISTS "idk_korisni_linkovi" (
  "kl_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kl_naziv" text NOT NULL,
  "kl_detaljni_opis" text,
  "kl_link" text NOT NULL,
  "kl_datetime" timestamp NOT NULL,
  "kl_employee_id" int NOT NULL,
  "kl_status" int NOT NULL DEFAULT '0',
  PRIMARY KEY (kl_id)
);

CREATE TABLE IF NOT EXISTS "idk_link_generator" (
  "lg_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lg_link_prijave" varchar(255) DEFAULT NULL,
  "idk_urlimg_prijave" varchar(500) DEFAULT NULL,
  "lg_url" varchar(255) NOT NULL,
  "lg_desc" varchar(255) NOT NULL,
  "lg_status" int NOT NULL DEFAULT '0',
  "lg_employeeid" int NOT NULL,
  "lg_datetime" timestamp NOT NULL,
  "lg_project" int DEFAULT NULL,
  "lg_nalogid" int DEFAULT NULL,
  "lg_language" varchar(20) DEFAULT 'bs',
  "lg_troskovi" double precision DEFAULT NULL,
  "lg_broj_pregleda" int NOT NULL DEFAULT '0',
  "lg_partner_app" int NOT NULL DEFAULT '0',
  PRIMARY KEY (lg_id)
);
CREATE INDEX IF NOT EXISTS "lg_nalogid" ON "idk_link_generator" (lg_nalogid);

CREATE TABLE IF NOT EXISTS "idk_link_generator_rel" (
  "lr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lr_lgid" int NOT NULL,
  "lr_groupid" int NOT NULL,
  PRIMARY KEY (lr_id)
);

CREATE TABLE IF NOT EXISTS "idk_link_projects" (
  "lp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lp_linkid" int NOT NULL,
  "lp_projectid" int NOT NULL,
  PRIMARY KEY (lp_id)
);

CREATE TABLE IF NOT EXISTS "idk_log_kandidat_statusi" (
  "lks_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lks_kandidat_id" int NOT NULL,
  "lks_status_obrade" int NOT NULL,
  "lks_status_messenger" int NOT NULL,
  "lks_datetime" timestamp NOT NULL,
  "lks_employee_id" int DEFAULT NULL,
  "lks_broj_dana" int DEFAULT NULL,
  "lks_link_id" int DEFAULT NULL,
  PRIMARY KEY (lks_id)
);
CREATE INDEX IF NOT EXISTS "lks_link_id" ON "idk_log_kandidat_statusi" (lks_link_id);
CREATE INDEX IF NOT EXISTS "lks_kandidat_id" ON "idk_log_kandidat_statusi" (lks_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_log_statusi_prijave" (
  "lsp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lsp_kandidat_id" int NOT NULL,
  "lsp_projekt_id" int DEFAULT NULL,
  "lsp_status_prijave_id" int NOT NULL,
  "lsp_employee_id" int DEFAULT NULL,
  "lsp_izvor" int NOT NULL,
  "lsp_datetime" timestamp NOT NULL,
  "lsp_broj_dana" int DEFAULT NULL,
  PRIMARY KEY (lsp_id)
);
CREATE INDEX IF NOT EXISTS "lsp_kandidat_id" ON "idk_log_statusi_prijave" (lsp_kandidat_id);
CREATE INDEX IF NOT EXISTS "lsp_status_prijave_id" ON "idk_log_statusi_prijave" (lsp_status_prijave_id);
CREATE INDEX IF NOT EXISTS "lsp_status_prijave_id_2" ON "idk_log_statusi_prijave" (lsp_status_prijave_id);
CREATE INDEX IF NOT EXISTS "lsp_projekt_id" ON "idk_log_statusi_prijave" (lsp_projekt_id);

CREATE TABLE IF NOT EXISTS "idk_logs" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "log_employeeid" int NOT NULL,
  "log_desc" text NOT NULL,
  "log_date" timestamp NOT NULL,
  "log_type" int NOT NULL DEFAULT '0',
  PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS "idk_messages" (
  "message_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "message_subject" varchar(150) NOT NULL,
  "message_text" text NOT NULL,
  "message_sentid" int NOT NULL,
  "message_status" int NOT NULL,
  "message_datetime" timestamp NOT NULL,
  PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS "idk_messages_users" (
  "mu_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mu_messageid" int NOT NULL,
  "mu_employeeid" int NOT NULL,
  "mu_status" int NOT NULL,
  PRIMARY KEY (mu_id)
);

CREATE TABLE IF NOT EXISTS "idk_messenger_obavijesti" (
  "mo_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mo_kandidat_id" int NOT NULL,
  "mo_tip" int NOT NULL,
  "mo_datum_slanja" timestamp NOT NULL,
  PRIMARY KEY (mo_id)
);

CREATE TABLE IF NOT EXISTS "idk_module_permissions" (
  "mp_id" int NOT NULL,
  "mp_name" varchar(255) NOT NULL,
  "mp_employees" varchar(255) DEFAULT NULL,
  PRIMARY KEY (mp_id)
);

CREATE TABLE IF NOT EXISTS "idk_modules" (
  "module_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "module_name" varchar(150) NOT NULL,
  "module_status" int NOT NULL,
  "module_desc" text NOT NULL,
  PRIMARY KEY (module_id)
);

CREATE TABLE IF NOT EXISTS "idk_nalog_financije" (
  "nf_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nf_nalog_id" int NOT NULL,
  "nf_datum_aktiviranja" date NOT NULL,
  "nf_type" int DEFAULT NULL,
  "nf_broj_rate" int DEFAULT NULL,
  "nf_iznos" double precision NOT NULL,
  "nf_placeno" int NOT NULL DEFAULT '0',
  "nf_datum_fakturisanja" date DEFAULT NULL,
  "nf_datum_placanja" date DEFAULT NULL,
  "nf_desc" varchar(255) DEFAULT NULL,
  PRIMARY KEY (nf_id)
);

CREATE TABLE IF NOT EXISTS "idk_nalog_profil" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv" varchar(250) NOT NULL,
  "zaposlenik" int NOT NULL,
  "status" int NOT NULL DEFAULT '1',
  "prioritet" int NOT NULL DEFAULT '1',
  "doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "nalog_id" int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "nalog_id" ON "idk_nalog_profil" (nalog_id);

CREATE TABLE IF NOT EXISTS "idk_nalog_smjer" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nalog_id" int NOT NULL,
  "smjer_id" int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_nalozi" (
  "nalog_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kompanija_id" int DEFAULT NULL,
  "employee_id" int DEFAULT NULL,
  "nalog_broj" varchar(255) DEFAULT NULL,
  "nalog_naziv" varchar(255) DEFAULT NULL,
  "nalog_opis" text,
  "nalog_kreirano" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "nalog_datum_potpisa_naloga" date DEFAULT NULL,
  "nalog_status" int DEFAULT NULL,
  "nalog_marketing_menadzer" int DEFAULT NULL,
  "nalog_ugovor" varchar(25) DEFAULT NULL,
  "nalog_potrebno_kandidata" int DEFAULT NULL,
  "nalog_provizija" double precision DEFAULT NULL,
  "nalog_provizija_po_plati" real DEFAULT NULL,
  "nalog_broj_rata" int DEFAULT NULL,
  "nalog_procenat_avansa" int DEFAULT NULL,
  "nalog_placa_nostrifikaciju" int NOT NULL DEFAULT '0',
  "nalog_nacin_nostrifikacije" int DEFAULT NULL,
  "nalog_provizija_nostrifikacija" double precision DEFAULT NULL,
  "nalog_broj_rata_nostrifikacija" int DEFAULT NULL,
  "nalog_firma_fakturisanja" int DEFAULT NULL,
  "nalog_placena_prva_rata" int NOT NULL DEFAULT '2',
  "nalog_financije" int NOT NULL DEFAULT '1',
  "nalog_akademija" int NOT NULL DEFAULT '0',
  "nalog_provizija_akademija" int DEFAULT NULL,
  "nalog_nacin_akademija" int DEFAULT NULL,
  "nalog_broj_dana_akademija" int DEFAULT NULL,
  "nalog_partner_active" int NOT NULL DEFAULT '0',
  "nalog_partner_provizija" double precision DEFAULT NULL,
  "pristup_poslodavcima" int NOT NULL DEFAULT '0',
  "partneri_pp" int NOT NULL DEFAULT '0',
  "nalog_prioritet" int DEFAULT NULL,
  "nalog_slanje_na_glosu" int NOT NULL DEFAULT '0',
  "nalog_dospijece" int NOT NULL DEFAULT '0',
  "nalog_smjerovi_kriterij" int NOT NULL DEFAULT '0',
  "nalog_js_partner_id" int DEFAULT NULL,
  "nalog_partner_app_title" varchar(255) DEFAULT NULL,
  "nalog_partner_app_location" varchar(255) DEFAULT NULL,
  "nalog_partner_app_until" timestamp DEFAULT NULL,
  "nalog_partner_app_salary" varchar(255) DEFAULT NULL,
  "nalog_poslodavac_trazi_jezik" int NOT NULL DEFAULT '0',
  "nalog_poslodavac_koristi_pp" int NOT NULL DEFAULT '0',
  "offers_and_benefits_of_employers" text,
  PRIMARY KEY (nalog_id)
);
CREATE INDEX IF NOT EXISTS "nalog_prioritet" ON "idk_nalozi" (nalog_prioritet);

CREATE TABLE IF NOT EXISTS "idk_nalozi_blokovi_prijave" (
  "nbp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nbp_nalogid" int NOT NULL,
  "nbp_vozacka" varchar(50) NOT NULL DEFAULT 'block',
  "nbp_vozacka_kategorija" varchar(255) DEFAULT NULL,
  "nbp_visoko_obr" int NOT NULL DEFAULT '1',
  "nbp_dodatno_obr" int NOT NULL DEFAULT '1',
  "nbp_korak4" int NOT NULL DEFAULT '1',
  "nbp_njemacki_jezik" varchar(10) NOT NULL DEFAULT 'BZ',
  "nbp_ostali_jezici" varchar(50) NOT NULL DEFAULT 'block',
  "nbp_korak7" int NOT NULL DEFAULT '1',
  "nbp_slika" int NOT NULL DEFAULT '0',
  "nbp_diploma" int NOT NULL DEFAULT '0',
  "nbp_pripravnicki" int NOT NULL DEFAULT '0',
  "nbp_strucni" int NOT NULL DEFAULT '0',
  "nbp_jezik_cert" int NOT NULL DEFAULT '0',
  "nbp_struka" varchar(50) DEFAULT NULL,
  "nbp_iskustvo_u_struci" int NOT NULL DEFAULT '0',
  "nbp_iskustvo_u_struci_trajanje" int DEFAULT NULL,
  "nbp_kandidat_starost_od" int DEFAULT NULL,
  "nbp_kandidat_starost_do" int DEFAULT NULL,
  PRIMARY KEY (nbp_id)
);

CREATE TABLE IF NOT EXISTS "idk_nalozi_log" (
  "n_log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "n_log_nalogid" int NOT NULL,
  "n_log_employeeid" int NOT NULL,
  "n_log_status" int NOT NULL,
  "n_log_vrijeme" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (n_log_id)
);

CREATE TABLE IF NOT EXISTS "idk_nalozi_opis" (
  "no_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "no_lang" varchar(255) NOT NULL,
  "no_nalogid" int NOT NULL,
  "no_nalognaziv" varchar(255) NOT NULL,
  "no_nalogopis" text NOT NULL,
  PRIMARY KEY (no_id)
);

CREATE TABLE IF NOT EXISTS "idk_nalozi_rate" (
  "nr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nr_nalog" int NOT NULL,
  "nr_rata" int NOT NULL,
  "nr_procenat" int DEFAULT NULL,
  "nr_vrijeme_placanja" varchar(35) DEFAULT NULL,
  "nr_datum" date DEFAULT NULL,
  "nr_mjeseci_nakon" int DEFAULT NULL,
  PRIMARY KEY (nr_id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_cron_export" (
  "id_c" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_c" int DEFAULT NULL,
  "result_c" text,
  "datetime_c" timestamp DEFAULT NULL,
  "date_c" date DEFAULT NULL,
  "sending_type_c" int DEFAULT NULL,
  "sent_to_employees_c" text,
  "download_employees_c" text,
  "settings_id" int DEFAULT NULL,
  PRIMARY KEY (id_c)
);

CREATE TABLE IF NOT EXISTS "idk_nd_cron_settings" (
  "id_s" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_s" int DEFAULT NULL,
  "status_s" int DEFAULT NULL,
  "employees_s" text,
  "control_employees_s" text,
  "candidate_status_s" int DEFAULT NULL,
  "status_days_s" int DEFAULT NULL,
  "communication_days_s" int DEFAULT NULL,
  "start_day_s" timestamp DEFAULT NULL,
  "end_day_s" timestamp DEFAULT NULL,
  PRIMARY KEY (id_s)
);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidata" (
  "id_broj_nd_kandidata" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ime_nd_kandidata" varchar(30) DEFAULT NULL,
  "prezime_nd_kandidata" varchar(50) DEFAULT NULL,
  "ulica_nd_kandidata" varchar(100) DEFAULT NULL,
  "postanski_broj_nd_kandidata" int DEFAULT NULL,
  "grad_nd_kandidata" varchar(100) DEFAULT NULL,
  "ulica_bor_nd_kandidata" varchar(100) DEFAULT NULL,
  "postanski_broj_bor_nd_kandidata" int DEFAULT NULL,
  "grad_bor_nd_kandidata" varchar(100) DEFAULT NULL,
  "mobilni_nd_kandidata" varchar(20) DEFAULT NULL,
  "email_nd_kandidata" varchar(50) DEFAULT NULL,
  "izdao_licnu_nd_kandidata" varchar(100) DEFAULT NULL,
  "jmbg_nd_kandidata" varchar(50) DEFAULT NULL,
  "broj_licne_karte_nd_kandidata" varchar(30) DEFAULT NULL,
  "skola_nd_kandidata" int DEFAULT NULL,
  "skola_smjer_nd_kandidata" int DEFAULT NULL,
  "poslodavac_nd_kandidata" int DEFAULT NULL,
  "poslodavac_nas_nd_kandidata" int DEFAULT NULL,
  "poslodavac_naziv_nas_nd_kandidata" int DEFAULT NULL,
  "poslodavac_naziv_nd_kandidata" varchar(200) DEFAULT NULL,
  "poslodavac_ulica_nd_kandidata" varchar(150) DEFAULT NULL,
  "poslodavac_postanski_broj_nd_kandidata" int DEFAULT NULL,
  "poslodavac_grad_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_regija_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_drzava_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_ime_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_prezime_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_mail_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_mobilni_nd_kandidata" varchar(50) DEFAULT NULL,
  "komentar_nd_kandidata" text,
  "vrijeme_kreiranja_nd_kandidata" timestamp DEFAULT NULL,
  "dodao_zaposlenik_nd_kandidata" int DEFAULT NULL,
  "zaduzen_zaposlenik_nd_kandidata" int DEFAULT NULL,
  "tim_nd_kandidata" int NOT NULL DEFAULT '0',
  "status_nd_kandidata" int DEFAULT NULL,
  "pstatus_nd_kandidata" int NOT NULL DEFAULT '1',
  "idd_ustanova_nd" int DEFAULT NULL,
  "broj_zahtjeva_na_ustanovi_nd_kandidata" varchar(100) DEFAULT NULL,
  "idd_kontakt_ustanova_nd" int DEFAULT NULL,
  "tracking_number_nd_kandidata" varchar(100) DEFAULT NULL,
  "link_tracking_number_nd_kandidata" int DEFAULT NULL,
  "vrsta_ugovora_nd_kandidata" int DEFAULT NULL,
  "rata1_nd_kandidata" int NOT NULL DEFAULT '0',
  "rata1_vrijeme_nd_kandidata" timestamp DEFAULT NULL,
  "rata2_nd_kandidata" int NOT NULL DEFAULT '0',
  "rata2_vrijeme_nd_kandidata" timestamp DEFAULT NULL,
  "povijest_nd_kandidata" int NOT NULL DEFAULT '0',
  "povijest_vrsta_nd_kandidata" int DEFAULT NULL,
  "kandidat_idd" int DEFAULT NULL,
  "partner_nd_status" int DEFAULT NULL,
  "kampanja_id" int DEFAULT NULL,
  "datum_rodjenja" date DEFAULT NULL,
  "in_vici_dial" int NOT NULL DEFAULT '0',
  "status_pp" int NOT NULL DEFAULT '3',
  "vrijeme_zakaznog_poziva" timestamp DEFAULT NULL,
  "status_zakaznog_poziva" int DEFAULT NULL,
  "zadnja_komunikacija" timestamp DEFAULT NULL,
  "chat_slike" text,
  "vrsta_obrade" int NOT NULL DEFAULT '0',
  "nivo_poznavanja_jezika" int NOT NULL DEFAULT '0',
  "certifikat_nd_kandidata" int NOT NULL DEFAULT '0',
  "inbound_aktivan" int NOT NULL DEFAULT '0',
  "poslan_spisak_datum" date DEFAULT NULL,
  "dokumentacija_kompletna_datum" date DEFAULT NULL,
  "na_prevodu_datum" date DEFAULT NULL,
  "prevod_zavrsen_datum" date DEFAULT NULL,
  "poslana_posta_datum" date DEFAULT NULL,
  "zaprimljena_dokumentacija_datum" date DEFAULT NULL,
  "stigla_taksa_dopuna_datum" date DEFAULT NULL,
  "placena_taksa_poslana_dopuna_datum" date DEFAULT NULL,
  "zavrsen_datum" date DEFAULT NULL,
  PRIMARY KEY (id_broj_nd_kandidata)
);
CREATE INDEX IF NOT EXISTS "kampanja_id" ON "idk_nd_kandidata" (kampanja_id);
CREATE INDEX IF NOT EXISTS "vrijeme_kreiranja_nd_kandidata" ON "idk_nd_kandidata" (vrijeme_kreiranja_nd_kandidata);
CREATE INDEX IF NOT EXISTS "status_nd_kandidata" ON "idk_nd_kandidata" (status_nd_kandidata);
CREATE INDEX IF NOT EXISTS "pstatus_nd_kandidata" ON "idk_nd_kandidata" (pstatus_nd_kandidata);
CREATE INDEX IF NOT EXISTS "povijest_nd_kandidata" ON "idk_nd_kandidata" (povijest_nd_kandidata);
CREATE INDEX IF NOT EXISTS "kandidat_idd" ON "idk_nd_kandidata" (kandidat_idd);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidata_biljeske" (
  "id_biljeska_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_kandidata_biljeska_nd" int DEFAULT NULL,
  "status_biljeska_nd" int DEFAULT NULL,
  "tip_biljeska_nd" int NOT NULL DEFAULT '1',
  "razlog_biljeska_nd" int DEFAULT NULL,
  "sadrzaj_biljeska_nd" text,
  "vrijeme_dodavanja_biljeska_nd" timestamp DEFAULT NULL,
  "vrijeme_grupa_biljeska_nd" int DEFAULT NULL,
  "dodao_zaposlenik_biljeska_nd" int DEFAULT NULL,
  "predracun_id" int DEFAULT NULL,
  "predracun_status" int DEFAULT NULL,
  "vrijeme_ponovnog_zvanja" timestamp DEFAULT NULL,
  "uplata_na_datum" timestamp DEFAULT NULL,
  "zadnja_inkaso_biljeska" int NOT NULL DEFAULT '0',
  "prilog_biljeska_nd" text,
  PRIMARY KEY (id_biljeska_nd)
);
CREATE INDEX IF NOT EXISTS "id_kandidata_biljeska_nd" ON "idk_nd_kandidata_biljeske" (id_kandidata_biljeska_nd);
CREATE INDEX IF NOT EXISTS "razlog_biljeska_nd" ON "idk_nd_kandidata_biljeske" (razlog_biljeska_nd);
CREATE INDEX IF NOT EXISTS "predracun_id" ON "idk_nd_kandidata_biljeske" (predracun_id);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidata_dokumenti" (
  "id_dokument_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_dokument_nd" varchar(100) DEFAULT NULL,
  "naziv_dokument_ostali_nd" varchar(300) DEFAULT NULL,
  "status_dokument_nd" int DEFAULT NULL,
  "id_kandidata_dokument_nd" int DEFAULT NULL,
  "vrijeme_dodavanja_dokument_nd" timestamp DEFAULT NULL,
  "dodao_zaposlenik_dokument_nd" int DEFAULT NULL,
  "tip_dokumenta" int DEFAULT NULL,
  "tip_dokumenta_status" int NOT NULL DEFAULT '1',
  "broj_rate" int NOT NULL DEFAULT '1',
  PRIMARY KEY (id_dokument_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidata_status_log" (
  "id_log_status_nd_kandidata" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "idd_broj_nd_kandidata" int DEFAULT NULL,
  "status_nd_kandidata" int DEFAULT NULL,
  "pstatus_nd_kandidata" int NOT NULL DEFAULT '1',
  "vrijeme_promjene_statusa_nd_kandidata" timestamp DEFAULT NULL,
  "broj_dana_statusa_nd_kandidata" int DEFAULT NULL,
  "promjenio_zaposlenik_nd_kandidata" int DEFAULT NULL,
  PRIMARY KEY (id_log_status_nd_kandidata)
);
CREATE INDEX IF NOT EXISTS "idd_broj_nd_kandidata" ON "idk_nd_kandidata_status_log" (idd_broj_nd_kandidata);
CREATE INDEX IF NOT EXISTS "broj_dana_statusa_nd_kandidata" ON "idk_nd_kandidata_status_log" (broj_dana_statusa_nd_kandidata);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidati_ciscenje" (
  "kandidat_ciscenje_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_kandidata_dipl" int NOT NULL,
  "ime_kandidata" varchar(255) NOT NULL,
  "prezime_kandidata" varchar(255) NOT NULL,
  "hash_id_dipl" varchar(255) NOT NULL,
  "status_informacija" int NOT NULL,
  "status_pracenja" int NOT NULL DEFAULT '0',
  "broj_telefona" varchar(255) NOT NULL,
  "id_kandidata_posao" int DEFAULT NULL,
  "arhiva" int NOT NULL DEFAULT '0',
  "treba_prebaciti_jezik_u_dipl" int DEFAULT NULL,
  "znanje_jezika_iz_idk_kan_jezici" varchar(255) DEFAULT NULL,
  "treba_prebaciti_skolu_smjer_u_dipl" int DEFAULT NULL,
  "skola" int DEFAULT NULL,
  "smjer" int DEFAULT NULL,
  PRIMARY KEY (kandidat_ciscenje_id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_limiti" (
  "lt_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lt_emp_id" int DEFAULT NULL,
  "lt_drzava" varchar(20) DEFAULT NULL,
  "lt_dnevni" int NOT NULL DEFAULT '0',
  "lt_sedmicni" int NOT NULL DEFAULT '0',
  "lt_mjesecni" int NOT NULL DEFAULT '0',
  "lt_dnevni_cnt" int NOT NULL DEFAULT '0',
  "lt_sedmicni_cnt" int NOT NULL DEFAULT '0',
  "lt_mjesecni_cnt" int NOT NULL DEFAULT '0',
  "lt_zadnji_dobio_bih" int DEFAULT NULL,
  "lt_zadnji_dobio_srb" int DEFAULT NULL,
  "lt_zadnji_dobio_de" int DEFAULT NULL,
  "lt_zadnji_dobio_ostalo" int DEFAULT NULL,
  "lt_campaign_category" varchar(15) NOT NULL DEFAULT 'C',
  PRIMARY KEY (lt_id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_menadzeri_statistike" (
  "id_stat" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "idd_broj_nd_kandidata" int DEFAULT NULL,
  "zaduzen_zaposlenik_id" int DEFAULT NULL,
  "prethodni_zaposlenik_id" int DEFAULT NULL,
  "vrsta_aktivnosti" int DEFAULT NULL,
  "vrijeme_aktivnosti" timestamp DEFAULT NULL,
  PRIMARY KEY (id_stat)
);

CREATE TABLE IF NOT EXISTS "idk_nd_naplata_preko" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naplata_preko" varchar(200) NOT NULL,
  "drzava" varchar(10) DEFAULT NULL,
  "fk_naplata_preko" int NOT NULL,
  "aktivno" int NOT NULL,
  "datum_aktivacije" timestamp DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_poste" (
  "id_poste" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_poste" varchar(100) DEFAULT NULL,
  "link_poste" text,
  PRIMARY KEY (id_poste)
);

CREATE TABLE IF NOT EXISTS "idk_nd_rate" (
  "id_r" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_nd_kan" int DEFAULT NULL,
  "br_r" int DEFAULT NULL,
  "vr_u_r" timestamp DEFAULT NULL,
  PRIMARY KEY (id_r)
);

CREATE TABLE IF NOT EXISTS "idk_nd_termini" (
  "termin_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "termin_kandidat_id" int DEFAULT NULL,
  "termin_vrijeme" timestamp DEFAULT NULL,
  "termin_kandidat_status" int DEFAULT NULL,
  "termin_kandidat_pstatus" int DEFAULT NULL,
  "termin_status" int DEFAULT NULL,
  "termin_zaposlenik_id" int DEFAULT NULL,
  "termin_biljeska_id" int DEFAULT NULL,
  PRIMARY KEY (termin_id)
);
CREATE INDEX IF NOT EXISTS "termin_kandidat_id" ON "idk_nd_termini" (termin_kandidat_id);
CREATE INDEX IF NOT EXISTS "termin_status" ON "idk_nd_termini" (termin_status);

CREATE TABLE IF NOT EXISTS "idk_nd_ugovori" (
  "ug_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ug_kandidat_id" int NOT NULL,
  "ug_broj" varchar(50) DEFAULT NULL,
  "ug_vrsta" int DEFAULT NULL,
  "ug_zaposlenik_id" int NOT NULL,
  "ug_token" varchar(50) NOT NULL,
  "ug_jezik" varchar(10) DEFAULT NULL,
  "ug_file" varchar(50) DEFAULT NULL,
  "ug_file_de" varchar(50) DEFAULT NULL,
  "ug_status" int NOT NULL,
  "ug_datum_arhiviranja" timestamp DEFAULT NULL,
  "ug_datum_slanja" timestamp NOT NULL,
  "ug_datum_prihvatanja" timestamp DEFAULT NULL,
  "ug_datum_odbijanja" timestamp DEFAULT NULL,
  "ug_datum_otvaranja_linka" timestamp DEFAULT NULL,
  "ug_ip_adresa" varchar(100) DEFAULT NULL,
  "ug_timestamp" varchar(30) DEFAULT NULL,
  "ug_razlog_odbijanja" int DEFAULT NULL,
  "ug_komentar" text,
  PRIMARY KEY (ug_id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove" (
  "id_ustanove_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_ustanove_nd" varchar(200) DEFAULT NULL,
  "ulica_ustanove_nd" varchar(100) DEFAULT NULL,
  "postanski_broj_ustanove_nd" int DEFAULT NULL,
  "grad_ustanove_nd" varchar(100) DEFAULT NULL,
  "regija_da_ne_ustanove_nd" int DEFAULT NULL,
  "naziv_regije_ustanove_nd" varchar(50) DEFAULT NULL,
  "drzava_ustanove_nd" varchar(100) DEFAULT NULL,
  "period_nostrifikacije_ustanove_nd" int DEFAULT NULL,
  "napomena_ustanove_nd" text,
  "datum_registracije_ustanove_nd" timestamp DEFAULT NULL,
  "dodao_zaposlenik_ustanove_nd" int DEFAULT NULL,
  PRIMARY KEY (id_ustanove_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove_biljeske" (
  "id_biljeska_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_ustanova_biljeska_nd" int DEFAULT NULL,
  "sadrzaj_biljeska_nd" text,
  "vrijeme_dodavanja_biljeska_nd" timestamp DEFAULT NULL,
  "vrijeme_grupa_biljeska_nd" int DEFAULT NULL,
  "dodao_zaposlenik_biljeska_nd" int DEFAULT NULL,
  PRIMARY KEY (id_biljeska_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove_kontakti" (
  "id_kontakt_ustanove_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ime_kontakt_ustanove_nd" varchar(100) DEFAULT NULL,
  "prezime_kontakt_ustanove_nd" varchar(150) DEFAULT NULL,
  "email_kontakt_ustanove_nd" varchar(200) DEFAULT NULL,
  "broj_telefona_kontakt_ustanove_nd" varchar(50) DEFAULT NULL,
  "zaduzenje_kontakt_ustanove_nd" text,
  "idd_ustanove_nd" int DEFAULT NULL,
  PRIMARY KEY (id_kontakt_ustanove_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove_skola" (
  "id_skole_ustanove_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "skola_idd" int DEFAULT NULL,
  "idd_ustanove_nd" int DEFAULT NULL,
  PRIMARY KEY (id_skole_ustanove_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove_skole_smjerovi" (
  "id_skole_smjer_ustanove_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "idd_skole_ustanove_nd" int DEFAULT NULL,
  "ss_idd" int DEFAULT NULL,
  PRIMARY KEY (id_skole_smjer_ustanove_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nd_ustanove_tip_dokumenta" (
  "id_tip_dokumenta_ustanove_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "povezanost_dokumenta_ustanove_nd" int DEFAULT NULL,
  "naziv_tip_dokumenta_ustanove_nd" varchar(200) DEFAULT NULL,
  "obaveznost_dokumenta_ustanove_nd" int DEFAULT NULL,
  "idd_ustanove_nd" int DEFAULT NULL,
  "idd_skole_ustanove_nd" int DEFAULT NULL,
  "idd_skole_smjer_ustanove_nd" int DEFAULT NULL,
  "template_dokumenta_ustanove_nd" int DEFAULT NULL,
  "template_naziv_dokumenta_ustanove_nd" varchar(100) DEFAULT NULL,
  PRIMARY KEY (id_tip_dokumenta_ustanove_nd)
);

CREATE TABLE IF NOT EXISTS "idk_nedostupan_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kandidat" int NOT NULL,
  "nalog" int NOT NULL,
  "agent" int NOT NULL,
  "brojac" int NOT NULL,
  "status" int NOT NULL,
  "doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_nostrifikovane_diplome" (
  "id_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_cand_dipl" int DEFAULT NULL,
  "id_cand_job" int DEFAULT NULL,
  "file_nd" text NOT NULL,
  "upload_date_nd" timestamp DEFAULT NULL,
  "upload_employee_id" int DEFAULT NULL,
  "full_recognition" int DEFAULT NULL,
  PRIMARY KEY (id_nd)
);
CREATE INDEX IF NOT EXISTS "id_cand_dipl" ON "idk_nostrifikovane_diplome" (id_cand_dipl);
CREATE INDEX IF NOT EXISTS "id_cand_job" ON "idk_nostrifikovane_diplome" (id_cand_job);

CREATE TABLE IF NOT EXISTS "idk_notes" (
  "note_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "note_txt" text NOT NULL,
  "note_files" text,
  "note_datetime" timestamp NOT NULL,
  "note_group" int NOT NULL,
  "note_dataid" int NOT NULL,
  "note_employeeid" int NOT NULL,
  PRIMARY KEY (note_id)
);

CREATE TABLE IF NOT EXISTS "idk_notification" (
  "not_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "not_kandidatid" int NOT NULL,
  "not_text" text NOT NULL,
  "not_url" varchar(255) NOT NULL,
  "not_date" timestamp NOT NULL,
  "not_type" int NOT NULL,
  "not_status" int NOT NULL,
  PRIMARY KEY (not_id)
);

CREATE TABLE IF NOT EXISTS "idk_notifications" (
  "notification_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "notification_datetime" timestamp NOT NULL,
  "notification_title" varchar(250) NOT NULL,
  "notification_icon" varchar(150) NOT NULL,
  "notification_link" varchar(250) NOT NULL,
  "notification_employeeid" int NOT NULL,
  "notification_status" int NOT NULL,
  PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS "idk_obracuni" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_id" int NOT NULL,
  "predracun_id" int NOT NULL,
  "status_predracuna" int NOT NULL DEFAULT '0',
  "status_obracuna" int NOT NULL DEFAULT '0',
  "valuta" varchar(10) NOT NULL,
  "rata" int NOT NULL,
  "broj_rata" int NOT NULL,
  "vrijednost_tipa" double precision NOT NULL,
  "vrijednost_kategorije" double precision NOT NULL,
  "iznos_obracuna_bam" double precision NOT NULL,
  "iznos_obracuna_rsd" double precision NOT NULL,
  "iznos_obracuna_eur" real NOT NULL,
  "vrijeme_kreiranja" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "vrijeme_uplate" timestamp DEFAULT NULL,
  "vrijeme_isplate" timestamp DEFAULT NULL,
  "tip_provizije" int NOT NULL,
  "kategorija_provizije" int DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_ostatci_obracuna" (
  "oo_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "oo_employee_id" int NOT NULL,
  "oo_valuta" varchar(10) NOT NULL,
  "oo_iznos" double precision NOT NULL,
  "oo_vrijeme_kreiranja" timestamp NOT NULL,
  "oo_period_od" timestamp NOT NULL,
  "oo_period_do" timestamp NOT NULL,
  "oo_status" int NOT NULL,
  PRIMARY KEY (oo_id)
);

CREATE TABLE IF NOT EXISTS "idk_otherdata" (
  "otherdata_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "otherdata_data" varchar(150) NOT NULL,
  "otherdata_group" int NOT NULL,
  PRIMARY KEY (otherdata_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_companies" (
  "pc_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pc_name" varchar(255) NOT NULL,
  "pc_primary_color" jsonb DEFAULT NULL,
  "pc_logo" varchar(255) DEFAULT NULL,
  PRIMARY KEY (pc_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_meetings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "meeting_appointment" timestamp NOT NULL,
  "meeting_type" varchar(255) NOT NULL DEFAULT '1',
  "meeting_company_id" int DEFAULT NULL,
  "meeting_employee" int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_notification" (
  "notification_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "notification_type_id" int NOT NULL,
  "notification_audience" varchar(255) NOT NULL,
  "notification_payload" text NOT NULL,
  "notification_sent_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "notification_created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "notification_title" text NOT NULL,
  "notification_content" text NOT NULL,
  "notification_partner_id" int DEFAULT NULL,
  "notification_action" varchar(255) NOT NULL,
  PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_notification_logs" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "employee_id" int NOT NULL,
  "title_de" varchar(255) NOT NULL,
  "content_de" varchar(255) NOT NULL,
  "title_en" varchar(255) NOT NULL,
  "content_en" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_notification_status" (
  "status_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "partner_id" int NOT NULL,
  "notification_id" int NOT NULL,
  "read_at" timestamp DEFAULT NULL,
  "deleted_at" timestamp DEFAULT NULL,
  PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_personal_notification_types" (
  "type_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "type_name" varchar(255) NOT NULL,
  PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_personal_notifications_preferences" (
  "preference_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "mute_all_notifications" boolean NOT NULL DEFAULT '0',
  "blocked_notification_types" text,
  "partner_id" int NOT NULL,
  PRIMARY KEY (preference_id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_pushnot" (
  "idk_ppid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "idk_partnerid" int DEFAULT NULL,
  "idk_partner_imeprezime" varchar(555) DEFAULT NULL,
  "idk_partner_telefon" varchar(555) DEFAULT NULL,
  "idk_partner_email" varchar(555) DEFAULT NULL,
  "idk_datum_registracije" varchar(555) DEFAULT NULL,
  PRIMARY KEY (idk_ppid)
);

CREATE TABLE IF NOT EXISTS "idk_partner_tutorials" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(100) NOT NULL,
  "file_name" varchar(50) NOT NULL,
  "is_default" boolean NOT NULL,
  "doe" timestamp NOT NULL,
  "employee_id" int NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_partner_uplate" (
  "jp_uplateid" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "jp_uplate_partnerid" int DEFAULT NULL,
  "jp_uplate_kandidatid" int DEFAULT NULL,
  "jp_uplate_status" int DEFAULT NULL,
  "jp_uplate_zaposlenikid" int DEFAULT NULL,
  "jp_uplate_datum" timestamp DEFAULT NULL,
  "jp_uplate_provizija" varchar(255) DEFAULT NULL,
  "jp_uplate_vrsta" int DEFAULT NULL,
  PRIMARY KEY (jp_uplateid)
);
CREATE INDEX IF NOT EXISTS "jp_uplate_kandidatid" ON "idk_partner_uplate" (jp_uplate_kandidatid);

CREATE TABLE IF NOT EXISTS "idk_partner_user_log" (
  "log_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "log_desc" varchar(255) NOT NULL,
  PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS "idk_ponovne_prijave" (
  "id_pp" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "porijeklo_pp" int DEFAULT NULL,
  "id_kandidata" int DEFAULT NULL,
  "employee_pp" int DEFAULT NULL,
  "datum_pp" timestamp DEFAULT NULL,
  "povijest_pp" int DEFAULT NULL,
  "povijest_vrsta_pp" int DEFAULT NULL,
  "kampanja_pp" int DEFAULT NULL,
  "opis_pp" text,
  PRIMARY KEY (id_pp)
);

CREATE TABLE IF NOT EXISTS "idk_poslovnice" (
  "branch_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "branch_name" varchar(150) NOT NULL,
  "branch_state" varchar(150) NOT NULL,
  "branch_city" varchar(150) NOT NULL,
  PRIMARY KEY (branch_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_appointment_groups" (
  "ppaq_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ppaq_start_date" date NOT NULL,
  "ppaq_end_date" date NOT NULL,
  "ppaq_casting_cron_executed" boolean NOT NULL DEFAULT '0',
  "ppaq_interview_cron_executed" boolean NOT NULL DEFAULT '0',
  "papq_name" varchar(200) DEFAULT NULL,
  "papq_name_de" varchar(200) DEFAULT NULL,
  "papq_nalog_id" varchar(7) DEFAULT NULL,
  PRIMARY KEY (ppaq_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_appointment_hours" (
  "pah_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pah_time" time NOT NULL,
  "pah_employee_id" int NOT NULL,
  "pah_doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pap_id" int NOT NULL,
  PRIMARY KEY (pah_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_appointments" (
  "pap_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pap_date" date DEFAULT NULL,
  "pap_nalog_id" int NOT NULL,
  "pap_city" varchar(100) DEFAULT NULL,
  "pap_location_name" text,
  "pap_google_maps_location" text,
  "pap_first_sending_number_days" int NOT NULL DEFAULT '0',
  "pap_second_sending_number_days" int NOT NULL DEFAULT '0',
  "pap_first_send_enabled" int NOT NULL DEFAULT '0',
  "pap_second_send_enabled" int NOT NULL DEFAULT '0',
  "pap_group_id" varchar(7) DEFAULT NULL,
  PRIMARY KEY (pap_id)
);
CREATE INDEX IF NOT EXISTS "pap_nalog_id" ON "idk_pp_appointments" (pap_nalog_id);

CREATE TABLE IF NOT EXISTS "idk_pp_appointments_questions" (
  "papq_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "papq_question_id" int NOT NULL,
  "papq_appointment_id" int NOT NULL,
  "papq_order" int DEFAULT NULL,
  PRIMARY KEY (papq_id)
);
CREATE INDEX IF NOT EXISTS "papq_question_id" ON "idk_pp_appointments_questions" (papq_question_id);
CREATE INDEX IF NOT EXISTS "papq_appointment_id" ON "idk_pp_appointments_questions" (papq_appointment_id);

CREATE TABLE IF NOT EXISTS "idk_pp_cand_appts" (
  "pca_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pca_appointment_id" int NOT NULL,
  "pca_kandidat_id" int NOT NULL,
  "pca_time" time DEFAULT NULL,
  "pca_avg_rating" double precision DEFAULT NULL,
  "pca_comment" text,
  "pca_interviewer" text,
  "pca_recommendation" int DEFAULT NULL,
  "pca_reason_recommendation" text,
  "pca_status" int NOT NULL DEFAULT '0',
  "pca_pah_id" int DEFAULT NULL,
  PRIMARY KEY (pca_id)
);
CREATE INDEX IF NOT EXISTS "pca_kandidat_id" ON "idk_pp_cand_appts" (pca_kandidat_id);
CREATE INDEX IF NOT EXISTS "pca_status" ON "idk_pp_cand_appts" (pca_status);

CREATE TABLE IF NOT EXISTS "idk_pp_cand_required_documents" (
  "crd_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "crd_cand_id" int NOT NULL,
  "crd_nalog_id" int DEFAULT NULL,
  "crd_type_id" int NOT NULL,
  "crd_done_by" int NOT NULL,
  "crd_status" int NOT NULL DEFAULT '1',
  "crd_date_activated" timestamp DEFAULT NULL,
  "crd_user_activated" int DEFAULT NULL,
  "crd_date_archived" timestamp DEFAULT NULL,
  "crd_user_archived" int DEFAULT NULL,
  "crd_comment" text,
  "crd_vi_id" int DEFAULT NULL,
  PRIMARY KEY (crd_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_city" (
  "pc_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pc_region" int NOT NULL,
  "pc_name" varchar(255) NOT NULL,
  "pc_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (pc_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_contract_sent" (
  "id_cs" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "cs_kandidat_id" int NOT NULL,
  "cs_nalog_id" int NOT NULL,
  "cs_partner_id" int NOT NULL,
  "cs_tracking_code" text,
  "cs_tracking_link" text,
  "cs_sent_date" date DEFAULT NULL,
  "cs_status" int NOT NULL,
  "cs_entry_date" timestamp DEFAULT NULL,
  "cs_entry_pua_id" int DEFAULT NULL,
  "cs_entry_employee_id" int DEFAULT NULL,
  "cs_received_date" date DEFAULT NULL,
  "cs_received_employee_id" int DEFAULT NULL,
  "cs_archived_date" timestamp DEFAULT NULL,
  "cs_archived_employee_id" int DEFAULT NULL,
  PRIMARY KEY (id_cs)
);
CREATE INDEX IF NOT EXISTS "cs_kandidat_id" ON "idk_pp_contract_sent" (cs_kandidat_id);
CREATE INDEX IF NOT EXISTS "cs_nalog_id" ON "idk_pp_contract_sent" (cs_nalog_id);
CREATE INDEX IF NOT EXISTS "cs_partner_id" ON "idk_pp_contract_sent" (cs_partner_id);
CREATE INDEX IF NOT EXISTS "cs_entry_pua_id" ON "idk_pp_contract_sent" (cs_entry_pua_id);

CREATE TABLE IF NOT EXISTS "idk_pp_document_types" (
  "doc_type_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "doc_type_name" varchar(400) DEFAULT NULL,
  "doc_type_name_de" varchar(400) DEFAULT NULL,
  "doc_type_date" timestamp DEFAULT NULL,
  "doc_type_entered_user" int NOT NULL DEFAULT '0',
  PRIMARY KEY (doc_type_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_documents" (
  "doc_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "doc_file_name" varchar(512) DEFAULT NULL,
  "doc_candidate_id" int NOT NULL,
  "doc_nalog_id" int DEFAULT NULL,
  "doc_partner_id" int DEFAULT NULL,
  "doc_visibility_status" int NOT NULL DEFAULT '2',
  "doc_nrd_id" int DEFAULT NULL,
  "doc_crd_id" int DEFAULT NULL,
  "doc_status" int NOT NULL DEFAULT '0',
  PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_documents_status_logs" (
  "dsl_doc_id" int NOT NULL,
  "dsl_doc_status" int NOT NULL,
  "dsl_date" timestamp NOT NULL,
  "dsl_user_id" int DEFAULT NULL,
  "dsl_pp_user_id" int DEFAULT NULL,
  "dsl_days_count" int DEFAULT NULL,
  "dsl_comment" text,
  PRIMARY KEY (dsl_doc_id,dsl_doc_status)
);

CREATE TABLE IF NOT EXISTS "idk_pp_documents_statuses" (
  "ds_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ds_name" varchar(50) NOT NULL,
  "ds_name_de" varchar(250) DEFAULT NULL,
  "ds_name_pp" varchar(250) DEFAULT NULL,
  "ds_name_de_pp" varchar(250) DEFAULT NULL,
  "ds_order" int DEFAULT NULL,
  PRIMARY KEY (ds_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_informacije_profil" (
  "pip_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pip_name" varchar(255) NOT NULL,
  "pip_name_de" varchar(255) NOT NULL,
  "pip_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (pip_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_nalog_profil" (
  "pnp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pnp_nalog_id" int NOT NULL,
  "pnp_info_id" int NOT NULL,
  PRIMARY KEY (pnp_id)
);
CREATE INDEX IF NOT EXISTS "pnp_nalog_id" ON "idk_pp_nalog_profil" (pnp_nalog_id);
CREATE INDEX IF NOT EXISTS "pnp_info_id" ON "idk_pp_nalog_profil" (pnp_info_id);

CREATE TABLE IF NOT EXISTS "idk_pp_nalog_required_documents" (
  "nrd_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "nrd_nalog_id" int NOT NULL,
  "nrd_type_id" int NOT NULL,
  "nrd_done_by" int NOT NULL,
  "nrd_status" int NOT NULL DEFAULT '1',
  "nrd_date_activated" timestamp DEFAULT NULL,
  "nrd_user_activated" int DEFAULT NULL,
  "nrd_date_archived" timestamp DEFAULT NULL,
  "nrd_user_archived" int DEFAULT NULL,
  "nrd_comment" text,
  "nrd_skilled_candidates" int NOT NULL DEFAULT '1',
  "nrd_west_balkan" int NOT NULL DEFAULT '0',
  "nrd_work_experience" int NOT NULL DEFAULT '0',
  PRIMARY KEY (nrd_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_partners" (
  "ppa_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ppa_nalog_id" int DEFAULT NULL,
  "ppa_company_id" int DEFAULT NULL,
  "ppa_status" int NOT NULL DEFAULT '1',
  "ppa_number_of_candidates" int DEFAULT NULL,
  PRIMARY KEY (ppa_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_permissions" (
  "ppe_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ppe_type" int DEFAULT NULL,
  "ppe_menu" text,
  "ppe_title" text,
  PRIMARY KEY (ppe_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_question_categories" (
  "pqc_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pqc_name" text NOT NULL,
  "pqc_name_de" text NOT NULL,
  PRIMARY KEY (pqc_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_question_options" (
  "pqo_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pqo_question_id" int NOT NULL,
  "pqo_value" int NOT NULL,
  "pqo_value_text" text NOT NULL,
  "pqo_value_text_de" text NOT NULL,
  "pqo_value_subtext" text,
  "pqo_value_subtext_de" text,
  PRIMARY KEY (pqo_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_questions" (
  "pqu_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pqu_question" text NOT NULL,
  "pqu_nalog_id" int NOT NULL,
  "pqu_user_id" int DEFAULT NULL,
  "pqu_category_id" int DEFAULT NULL,
  "pqu_has_text" int NOT NULL DEFAULT '1',
  "pqu_has_rating" int NOT NULL DEFAULT '1',
  "pqu_has_dropdown" int NOT NULL DEFAULT '0',
  "pqu_export_order" int DEFAULT NULL,
  PRIMARY KEY (pqu_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_ratings" (
  "pra_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pra_rating" int DEFAULT NULL,
  "pra_comment" text,
  "pra_options_value" int DEFAULT NULL,
  "pra_appointment_question_id" int NOT NULL,
  "pra_kandidat_id" int NOT NULL,
  PRIMARY KEY (pra_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_regions" (
  "pr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pr_name" varchar(255) NOT NULL,
  "pr_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (pr_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_reminder_documents" (
  "prd_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "prd_prs_id" int NOT NULL,
  "prd_nrd_id" int DEFAULT NULL,
  "prd_crd_id" int DEFAULT NULL,
  "prd_day_freq" int NOT NULL,
  "prd_create_after" int NOT NULL,
  "prd_active" int NOT NULL DEFAULT '1',
  PRIMARY KEY (prd_id)
);
CREATE INDEX IF NOT EXISTS "prd_nrd_id" ON "idk_pp_reminder_documents" (prd_nrd_id);
CREATE INDEX IF NOT EXISTS "prd_crd_id" ON "idk_pp_reminder_documents" (prd_crd_id);
CREATE INDEX IF NOT EXISTS "prd_prs_id" ON "idk_pp_reminder_documents" (prd_prs_id);

CREATE TABLE IF NOT EXISTS "idk_pp_reminder_settings" (
  "prs_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "prs_nalog_id" int NOT NULL,
  "prs_partner_id" int DEFAULT NULL,
  "prs_reminder_type_id" int NOT NULL,
  "prs_pua_ids" varchar(500) DEFAULT NULL,
  "prs_controlling_pua_ids" varchar(500) DEFAULT NULL,
  "prs_employee_ids" varchar(50) DEFAULT NULL,
  "prs_controlling_employee_ids" varchar(50) DEFAULT NULL,
  "prs_active" int NOT NULL DEFAULT '1',
  "prs_first_trigger_date" date DEFAULT NULL,
  "prs_create_after" int DEFAULT NULL,
  PRIMARY KEY (prs_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_reminder_types" (
  "prt_id" int NOT NULL,
  "prt_name" varchar(100) NOT NULL,
  "prt_user_type" int NOT NULL,
  "prt_day_freq" int NOT NULL,
  "prt_controling" int NOT NULL DEFAULT '0',
  "prt_mail_subject_de" varchar(100) DEFAULT NULL,
  "prt_mail_text_de" text NOT NULL,
  "prt_notification_text_de" text,
  "prt_has_documents" int NOT NULL DEFAULT '0',
  PRIMARY KEY (prt_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_reminders" (
  "pr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pr_reminder_setting_id" int DEFAULT NULL,
  "pr_reminder_document_id" int DEFAULT NULL,
  "pr_candidate_id" int NOT NULL,
  "pr_level" int NOT NULL DEFAULT '1',
  "pr_date_sent" timestamp NOT NULL,
  "pr_users_sent" varchar(500) NOT NULL,
  "pr_user_assigned" int DEFAULT NULL,
  "pr_done_by_crm_employee" int DEFAULT NULL,
  "pr_date_assigned" timestamp DEFAULT NULL,
  "pr_date_completed" timestamp DEFAULT NULL,
  "pr_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (pr_id)
);
CREATE INDEX IF NOT EXISTS "pr_reminder_setting_id" ON "idk_pp_reminders" (pr_reminder_setting_id);
CREATE INDEX IF NOT EXISTS "pr_reminder_document_id" ON "idk_pp_reminders" (pr_reminder_document_id);

CREATE TABLE IF NOT EXISTS "idk_pp_user_access" (
  "pua_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pua_type" int DEFAULT NULL,
  "pua_partner_id" int DEFAULT NULL,
  "pua_nalog_id" int DEFAULT NULL,
  "pua_user_id" int DEFAULT NULL,
  "pua_permission_id" int DEFAULT NULL,
  "pua_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (pua_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_users" (
  "pu_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pu_status" int NOT NULL DEFAULT '1',
  "pu_fname" varchar(100) DEFAULT NULL,
  "pu_lname" varchar(150) DEFAULT NULL,
  "pu_email" varchar(200) DEFAULT NULL,
  "pu_password" varchar(250) DEFAULT NULL,
  "pu_key" varchar(250) DEFAULT NULL,
  "pu_language" int NOT NULL DEFAULT '1',
  "pu_gender" varchar(7) DEFAULT NULL,
  "pu_company_id" int DEFAULT NULL,
  PRIMARY KEY (pu_id)
);

CREATE TABLE IF NOT EXISTS "idk_pp_visa_incomplete" (
  "vi_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "vi_cand_id" int NOT NULL,
  "vi_type" int NOT NULL,
  "vi_complaint" int NOT NULL DEFAULT '0',
  "vi_status" int NOT NULL,
  "vi_date_received_candidate" timestamp DEFAULT NULL,
  "vi_date_we_received_candidate" timestamp DEFAULT NULL,
  "vi_deadline_date_candidate" date DEFAULT NULL,
  "vi_date_received_employer" timestamp DEFAULT NULL,
  "vi_date_we_received_employer" timestamp DEFAULT NULL,
  "vi_deadline_date_employer" date DEFAULT NULL,
  "vi_nalog_id" int DEFAULT NULL,
  "vi_pp_partner_id" int DEFAULT NULL,
  PRIMARY KEY (vi_id)
);

CREATE TABLE IF NOT EXISTS "idk_predracuni" (
  "pr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pr_naplata_preko" int NOT NULL DEFAULT '0',
  "pr_kandidat_id" int NOT NULL,
  "pr_broj_predracuna" varchar(50) NOT NULL,
  "pr_datum_kreiranja" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "pr_zaposlenik" int NOT NULL,
  "pr_vrsta_predracuna" int NOT NULL,
  "pr_rata" int NOT NULL,
  "pr_status" int NOT NULL DEFAULT '1',
  "pr_domaca_valuta" varchar(50) NOT NULL,
  "pr_vrijednost_BAM" double precision NOT NULL,
  "pr_vrijednost_RSD" double precision NOT NULL,
  "pr_vrijednost_EUR" double precision NOT NULL,
  "pr_file" varchar(100) DEFAULT NULL,
  "pr_file_de" varchar(100) DEFAULT NULL,
  "pr_uplaceno" int NOT NULL DEFAULT '0',
  "pr_datum_uplate" date DEFAULT NULL,
  "pr_opis" varchar(255) DEFAULT NULL,
  "pr_stornirano" int NOT NULL DEFAULT '0',
  "pr_datum_storniranja" timestamp DEFAULT NULL,
  "pr_vrsta_placanja" int DEFAULT NULL,
  "pr_izdan_racun" int NOT NULL DEFAULT '0',
  "pr_stari_ink_status" int DEFAULT NULL,
  "pr_inkaso_agent" int DEFAULT NULL,
  PRIMARY KEY (pr_id)
);
CREATE INDEX IF NOT EXISTS "pr_kandidat_id" ON "idk_predracuni" (pr_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_profil_kriterij" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "vozacka_dozvola" int NOT NULL,
  "kategorija_vozacke_dozvole" varchar(50) DEFAULT NULL,
  "smjerovi_naloga" int NOT NULL,
  "radno_iskustvo_struka" int NOT NULL,
  "radno_iskustvo_struka_trajanje" int DEFAULT NULL,
  "starost" int NOT NULL,
  "starost_minimum" int DEFAULT NULL,
  "starost_maksimum" int DEFAULT NULL,
  "njemacki_jezik" int NOT NULL,
  "nivo_njemackog_jezika" varchar(11) DEFAULT NULL,
  "znanje_drugog_jezika" int NOT NULL,
  "engleski_jezik" int DEFAULT NULL,
  "nivo_engleskog_jezika" varchar(11) DEFAULT NULL,
  "francuski_jezik" int DEFAULT NULL,
  "nivo_francuskog_jezika" varchar(11) DEFAULT NULL,
  "italijanski_jezik" int DEFAULT NULL,
  "nivo_italijanskog_jezika" varchar(11) DEFAULT NULL,
  "profil_id" int NOT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "profil_id" ON "idk_profil_kriterij" (profil_id);

CREATE TABLE IF NOT EXISTS "idk_project_candidate_queue" (
  "queue_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "queue_project_id" varchar(7) NOT NULL,
  "queue_candidate_id" varchar(7) NOT NULL,
  "queue_partner_id" int DEFAULT NULL,
  "queue_entry_date" timestamp NOT NULL,
  "queue_is_assigned" boolean NOT NULL DEFAULT '0',
  PRIMARY KEY (queue_id)
);

CREATE TABLE IF NOT EXISTS "idk_project_kandidati" (
  "pk_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pk_projectid" int NOT NULL,
  "pk_kandidatid" int NOT NULL,
  PRIMARY KEY (pk_id)
);
CREATE INDEX IF NOT EXISTS "pk_projectid" ON "idk_project_kandidati" (pk_projectid);
CREATE INDEX IF NOT EXISTS "pk_kandidatid" ON "idk_project_kandidati" (pk_kandidatid);

CREATE TABLE IF NOT EXISTS "idk_projects" (
  "project_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "project_order" int DEFAULT '0',
  "project_name" varchar(250) NOT NULL,
  "project_desc" text,
  "project_plannedhours" varchar(20) DEFAULT NULL,
  "project_companyid" int NOT NULL,
  "project_employeeid" int NOT NULL,
  "project_pmanagerid" int DEFAULT NULL,
  "project_datetime" timestamp NOT NULL,
  "project_status" int NOT NULL,
  "project_nalogid" varchar(25) DEFAULT '0',
  "project_datumtermina" date DEFAULT NULL,
  "project_datumterminado" date DEFAULT NULL,
  "project_eukandidati" int DEFAULT '0',
  PRIMARY KEY (project_id)
);
CREATE INDEX IF NOT EXISTS "project_nalogid" ON "idk_projects" (project_nalogid);

CREATE TABLE IF NOT EXISTS "idk_projects_settings" (
  "ps_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ps_name" varchar(150) NOT NULL,
  "ps_group" int NOT NULL,
  PRIMARY KEY (ps_id)
);

CREATE TABLE IF NOT EXISTS "idk_projects_tasks" (
  "pt_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pt_name" varchar(250) NOT NULL,
  "pt_desc" text,
  "pt_datetime" timestamp NOT NULL,
  "pt_duedatetime" timestamp DEFAULT NULL,
  "pt_projectid" int NOT NULL,
  "pt_employeeid" int DEFAULT NULL,
  "pt_box" int NOT NULL,
  "pt_sort" int NOT NULL,
  PRIMARY KEY (pt_id)
);

CREATE TABLE IF NOT EXISTS "idk_provider_for_sending_messages" (
  "psm_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "psm_group_type" int DEFAULT NULL,
  "psm_group_name" varchar(500) DEFAULT NULL,
  "psm_active_provider" int DEFAULT NULL,
  PRIMARY KEY (psm_id)
);

CREATE TABLE IF NOT EXISTS "idk_pushnotifications" (
  "pushnot_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "pushnot_datetime" timestamp NOT NULL,
  "pushnot_nalogid" int NOT NULL,
  "pushnot_employeeid" int NOT NULL,
  PRIMARY KEY (pushnot_id)
);

CREATE TABLE IF NOT EXISTS "idk_racuni" (
  "racun_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "predracun_id" varchar(11) DEFAULT NULL,
  "racun_broj" varchar(50) NOT NULL,
  "racun_kandidat_id" int NOT NULL,
  "racun_datum_kreiranja" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "racun_vrsta_racuna" int NOT NULL DEFAULT '0',
  "racun_status" int NOT NULL DEFAULT '1',
  "racun_domaca_valuta" varchar(50) NOT NULL,
  "racun_vrijednost_BAM" double precision NOT NULL,
  "racun_vrijednost_RSD" double precision NOT NULL,
  "racun_vrijednost_EUR" double precision NOT NULL,
  "racun_file" varchar(255) NOT NULL DEFAULT '',
  "racun_file_de" varchar(255) NOT NULL DEFAULT '',
  "racun_uplaceno" int NOT NULL DEFAULT '0',
  "racun_datum_uplate" date DEFAULT NULL,
  "racun_opis" text,
  "racun_stornirano" int DEFAULT '0',
  "racun_datum_storniranja" timestamp DEFAULT NULL,
  "racun_razlog_storniranja" int NOT NULL DEFAULT '0',
  "racun_komentar_storniranja" text,
  "racun_bf" varchar(25) DEFAULT NULL,
  PRIMARY KEY (racun_id)
);

CREATE TABLE IF NOT EXISTS "idk_razlozi_odbijanja" (
  "ro_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ro_naziv" text NOT NULL,
  "ro_naziv_de" varchar(255) NOT NULL,
  "ro_blok" varchar(255) NOT NULL,
  "ro_dio_bloka" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ro_id)
);

CREATE TABLE IF NOT EXISTS "idk_reject_reasons" (
  "rr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "rr_name_bs" text NOT NULL,
  "rr_name_de" text NOT NULL,
  "rr_name_en" text,
  "rr_rejected_by" int NOT NULL,
  "rr_user_id" int NOT NULL,
  "rr_status" int NOT NULL,
  "rr_doe" timestamp NOT NULL,
  PRIMARY KEY (rr_id)
);

CREATE TABLE IF NOT EXISTS "idk_reminders" (
  "reminder_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "reminder_type" int DEFAULT NULL,
  "reminder_candidate_id" int DEFAULT NULL,
  "reminder_date_time" timestamp DEFAULT NULL,
  "reminder_candidate_status" int DEFAULT NULL,
  "reminder_candidate_substatus" int DEFAULT NULL,
  "reminder_employee" int DEFAULT NULL,
  "reminder_status" int DEFAULT NULL,
  "reminder_foreign_key" int DEFAULT NULL,
  PRIMARY KEY (reminder_id)
);

CREATE TABLE IF NOT EXISTS "idk_ro_usluge" (
  "id_ro" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_ro_bs" text,
  "naziv_ro_sr" text,
  "naziv_ro_de" text,
  "tip_ro" int DEFAULT NULL,
  "status_ro" int DEFAULT NULL,
  "ponovno_zvanje_ro" int DEFAULT NULL,
  "br_dana_ro" int DEFAULT NULL,
  "odobrio_ro" int DEFAULT '11',
  "dodao_ro" int DEFAULT NULL,
  PRIMARY KEY (id_ro)
);

CREATE TABLE IF NOT EXISTS "idk_sales_reminders" (
  "sr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sr_employee_id" int NOT NULL,
  "sr_client_id" int NOT NULL,
  "sr_doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "sr_call_datetime" timestamp NOT NULL,
  "sr_status" int NOT NULL DEFAULT '1',
  "sr_type" int NOT NULL DEFAULT '0',
  PRIMARY KEY (sr_id)
);

CREATE TABLE IF NOT EXISTS "idk_settings" (
  "settings_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "settings_name" varchar(50) NOT NULL,
  "settings_title" varchar(100) NOT NULL,
  "settings_value" text NOT NULL,
  "settings_group" int NOT NULL,
  PRIMARY KEY (settings_id)
);

CREATE TABLE IF NOT EXISTS "idk_skladiste" (
  "skl_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "skl_branch" int NOT NULL DEFAULT '1',
  "skl_title" varchar(250) NOT NULL,
  "skl_desc" text,
  "skl_image" varchar(250) DEFAULT NULL,
  "skl_available" int NOT NULL,
  "skl_archive" int NOT NULL DEFAULT '0',
  "skl_kategorija" int DEFAULT NULL,
  "skl_datum_nabavke" date DEFAULT NULL,
  PRIMARY KEY (skl_id)
);

CREATE TABLE IF NOT EXISTS "idk_skladiste_kategorije" (
  "isk_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "isk_naziv_kategorije" varchar(50) NOT NULL,
  PRIMARY KEY (isk_id)
);

CREATE TABLE IF NOT EXISTS "idk_skladiste_product" (
  "isp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "isp_skl_id" int NOT NULL,
  "isp_serijski_broj" varchar(150) NOT NULL,
  "isp_dodatni_info" text NOT NULL,
  "isp_razlozi_odbijanja" text,
  "isp_razlozi_razduzivanja" text,
  "isp_archive" int NOT NULL DEFAULT '0',
  "isp_inventar" int NOT NULL DEFAULT '0',
  PRIMARY KEY (isp_id)
);

CREATE TABLE IF NOT EXISTS "idk_skladiste_zaposlenici" (
  "isz_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "isz_sklid" int NOT NULL,
  "sz_employeeid" int NOT NULL,
  "sz_quantity" int NOT NULL DEFAULT '1',
  "sz_branch" int NOT NULL DEFAULT '0',
  "sz_opis" varchar(250) NOT NULL,
  "isz_status" int NOT NULL DEFAULT '0',
  "isz_product_id" int NOT NULL,
  PRIMARY KEY (isz_id)
);

CREATE TABLE IF NOT EXISTS "idk_skole" (
  "skola_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "skola_naziv" varchar(255) NOT NULL,
  "skola_naziv_de" varchar(255) DEFAULT NULL,
  "skola_tip_obrazovanja" varchar(50) NOT NULL,
  PRIMARY KEY (skola_id)
);

CREATE TABLE IF NOT EXISTS "idk_skole_smjerovi" (
  "ss_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ss_naziv" varchar(255) NOT NULL,
  "ss_naziv_de" varchar(255) DEFAULT NULL,
  "ss_naziv_en" varchar(255) DEFAULT NULL,
  "ss_skola_id" int NOT NULL,
  "ss_trajanje_skole" int DEFAULT NULL,
  "ss_struka_id" int DEFAULT NULL,
  PRIMARY KEY (ss_id)
);

CREATE TABLE IF NOT EXISTS "idk_sms_messages" (
  "sms_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sms_origin" varchar(50) NOT NULL,
  "sms_number" varchar(100) NOT NULL,
  "sms_content" text NOT NULL,
  "sms_status" int NOT NULL,
  "sms_created_at" timestamp DEFAULT NULL,
  "sms_response_nthsmsid" text,
  "sms_response_statuscode" varchar(10) DEFAULT NULL,
  "sms_count" int DEFAULT NULL,
  "sms_updated_at" timestamp DEFAULT NULL,
  "sms_notification_statuscode" int DEFAULT NULL,
  "sms_notification_datetime" timestamp NOT NULL,
  "sms_type" int DEFAULT NULL,
  PRIMARY KEY (sms_id)
);

CREATE TABLE IF NOT EXISTS "idk_struke" (
  "id_struke" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_struke" varchar(255) NOT NULL,
  "naziv_struke_de" varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_struke)
);

CREATE TABLE IF NOT EXISTS "idk_task_force" (
  "tf_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tf_candidate_id" int NOT NULL,
  "tf_agent_id" int DEFAULT NULL,
  "tf_nalog_id" int NOT NULL,
  "tf_project_id" int NOT NULL,
  "tf_casting_id" int DEFAULT NULL,
  "tf_status_id" int NOT NULL,
  "tf_call_appointment" timestamp DEFAULT NULL,
  "tf_note" text,
  "tf_important_note" int NOT NULL,
  "tf_last_active_task" int NOT NULL,
  "tf_brojac_neuspjela_komunikacija" int DEFAULT NULL,
  "tf_files" text,
  "tf_doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "tf_vrsta_id" int NOT NULL DEFAULT '1',
  PRIMARY KEY (tf_id)
);
CREATE INDEX IF NOT EXISTS "tf_candidate_id" ON "idk_task_force" (tf_candidate_id);
CREATE INDEX IF NOT EXISTS "tf_agent_id" ON "idk_task_force" (tf_agent_id);
CREATE INDEX IF NOT EXISTS "tf_nalog_id" ON "idk_task_force" (tf_nalog_id);
CREATE INDEX IF NOT EXISTS "tf_project_id" ON "idk_task_force" (tf_project_id);
CREATE INDEX IF NOT EXISTS "tf_status_id" ON "idk_task_force" (tf_status_id);
CREATE INDEX IF NOT EXISTS "tf_casting_id" ON "idk_task_force" (tf_casting_id);
CREATE INDEX IF NOT EXISTS "tf_vrsta_id" ON "idk_task_force" (tf_vrsta_id);
CREATE INDEX IF NOT EXISTS "tf_last_active_task" ON "idk_task_force" (tf_last_active_task);

CREATE TABLE IF NOT EXISTS "idk_tasks" (
  "task_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_txt" text NOT NULL,
  "task_replytxt" text NOT NULL,
  "task_duedatetime" timestamp NOT NULL,
  "task_assignedid" int NOT NULL,
  "task_emailnotifi" int NOT NULL,
  "task_repeatnotifi" int NOT NULL,
  "task_group" int NOT NULL,
  "task_dataid" int NOT NULL,
  "task_employeeid" int NOT NULL,
  "task_datetime" timestamp NOT NULL,
  "task_status" int NOT NULL,
  PRIMARY KEY (task_id)
);

CREATE TABLE IF NOT EXISTS "idk_tf_agent_nalog" (
  "tfan_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tfan_nalog" int NOT NULL,
  "tfan_agent" int NOT NULL,
  "tfan_vrsta_id" int NOT NULL DEFAULT '1',
  PRIMARY KEY (tfan_id)
);
CREATE INDEX IF NOT EXISTS "tfan_nalog" ON "idk_tf_agent_nalog" (tfan_nalog);
CREATE INDEX IF NOT EXISTS "tfan_agent" ON "idk_tf_agent_nalog" (tfan_agent);
CREATE INDEX IF NOT EXISTS "tfan_vrsta_id" ON "idk_tf_agent_nalog" (tfan_vrsta_id);

CREATE TABLE IF NOT EXISTS "idk_tf_reservations" (
  "tf_kandidat_id" int NOT NULL,
  "tf_agent_id" int NOT NULL,
  "tf_projekt_id" int NOT NULL,
  "tf_nalog_id" int NOT NULL,
  "tf_vrsta_id" int NOT NULL DEFAULT '1',
  "tf_dipl_id" int DEFAULT NULL,
  "tf_category_id" int NOT NULL DEFAULT '1',
  PRIMARY KEY (tf_kandidat_id)
);

CREATE TABLE IF NOT EXISTS "idk_tf_stats_reservations" (
  "tsr_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tsr_candidate_id" int NOT NULL,
  "tsr_agent_id" int NOT NULL,
  "tsr_interview_id" int NOT NULL,
  "tsr_nalog_id" int NOT NULL,
  "tsr_link_id" int DEFAULT NULL,
  "tsr_status" int NOT NULL,
  PRIMARY KEY (tsr_id)
);
CREATE INDEX IF NOT EXISTS "tsr_candidate_id" ON "idk_tf_stats_reservations" (tsr_candidate_id);
CREATE INDEX IF NOT EXISTS "tsr_agent_id" ON "idk_tf_stats_reservations" (tsr_agent_id);
CREATE INDEX IF NOT EXISTS "tsr_status" ON "idk_tf_stats_reservations" (tsr_status);
CREATE INDEX IF NOT EXISTS "tsr_nalog_id" ON "idk_tf_stats_reservations" (tsr_nalog_id);
CREATE INDEX IF NOT EXISTS "tsr_interview_id" ON "idk_tf_stats_reservations" (tsr_interview_id);
CREATE INDEX IF NOT EXISTS "tsr_link_id" ON "idk_tf_stats_reservations" (tsr_link_id);

CREATE TABLE IF NOT EXISTS "idk_tf_statusi" (
  "tfs_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tfs_name" varchar(255) NOT NULL,
  "tfs_is_positive" int NOT NULL,
  "tfs_has_interview" int NOT NULL DEFAULT '0',
  "tfs_appointment" int NOT NULL,
  "tfs_order" int NOT NULL,
  "tfs_status_prijave" int DEFAULT NULL,
  "tfs_vrsta_id" int NOT NULL DEFAULT '1',
  PRIMARY KEY (tfs_id)
);
CREATE INDEX IF NOT EXISTS "tfs_vrsta_id" ON "idk_tf_statusi" (tfs_vrsta_id);

CREATE TABLE IF NOT EXISTS "idk_tf_transfered_candidates_logs" (
  "tcl_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tcl_transfered_candidates" text NOT NULL,
  "tcl_destination_project_id" int NOT NULL,
  "tcl_doe" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "tcl_employee_id" int NOT NULL,
  PRIMARY KEY (tcl_id)
);

CREATE TABLE IF NOT EXISTS "idk_tf_vrste" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "status" int NOT NULL,
  "category" int NOT NULL DEFAULT '1',
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "idk_ticketi" (
  "ticket_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ticket_status" int NOT NULL,
  "ticket_predmet" varchar(255) NOT NULL,
  "ticket_opis" text NOT NULL,
  "ticket_hitnost" int NOT NULL,
  "ticket_posiljaoc" int NOT NULL,
  "ticket_primatelj" int DEFAULT '0',
  "ticket_primatelj_odjel" int NOT NULL,
  "ticket_vrijeme_kreiranja" timestamp DEFAULT NULL,
  "ticket_vrijeme_prihvatanja" timestamp DEFAULT NULL,
  "ticket_vrijeme_zavrsetka" timestamp DEFAULT NULL,
  "ticket_dokument" varchar(255) DEFAULT NULL,
  PRIMARY KEY (ticket_id)
);

CREATE TABLE IF NOT EXISTS "idk_ticketi_komentari" (
  "ticket_k_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ticket_k_id_tiketa" int NOT NULL,
  "ticket_k_posiljaoc" int NOT NULL,
  "ticket_k_sadrzaj" text NOT NULL,
  "ticket_k_dokument" varchar(50) NOT NULL,
  "ticket_k_vrijeme_kreiranja" timestamp DEFAULT NULL,
  PRIMARY KEY (ticket_k_id)
);

CREATE TABLE IF NOT EXISTS "idk_timeline" (
  "timeline_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "timeline_type" int NOT NULL,
  "timeline_txt" text NOT NULL,
  "timeline_datetime" timestamp NOT NULL,
  "timeline_group" int NOT NULL,
  "timeline_dataid" int NOT NULL,
  "timeline_employeeid" int NOT NULL,
  PRIMARY KEY (timeline_id)
);

CREATE TABLE IF NOT EXISTS "idk_timovi" (
  "id_t" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_t" varchar(200) DEFAULT NULL,
  "skraceni_naziv_t" varchar(20) DEFAULT NULL,
  "boja_t" varchar(20) DEFAULT NULL,
  "datum_reg_t" timestamp DEFAULT NULL,
  "status_t" int DEFAULT NULL,
  PRIMARY KEY (id_t)
);

CREATE TABLE IF NOT EXISTS "idk_tipovi_provizija" (
  "tp_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tp_naziv" varchar(100) NOT NULL,
  "tp_iznos" double precision NOT NULL DEFAULT '0',
  "tp_iznos_rs" double precision NOT NULL DEFAULT '0',
  "tp_tip" int NOT NULL DEFAULT '1',
  "tp_tim" int NOT NULL DEFAULT '0',
  "tp_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (tp_id)
);

CREATE TABLE IF NOT EXISTS "idk_triggerurl" (
  "url_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "url_link" varchar(250) NOT NULL,
  "url_datetime" timestamp NOT NULL,
  "url_tag" varchar(50) NOT NULL,
  PRIMARY KEY (url_id)
);

CREATE TABLE IF NOT EXISTS "idk_tutorijali" (
  "tutorijal_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "tutorijal_kategorija_id" int DEFAULT NULL,
  "tutorijal_yt_url" text,
  "tutorijal_doc" text,
  "tutorijal_opis" text,
  PRIMARY KEY (tutorijal_id)
);
CREATE INDEX IF NOT EXISTS "tutorijal_kategorija_id" ON "idk_tutorijali" (tutorijal_kategorija_id);

CREATE TABLE IF NOT EXISTS "idk_validnosti_inputa" (
  "vi_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "vi_razlog_id" int DEFAULT NULL,
  "vi_kandidat_id" int NOT NULL,
  "vi_status" int DEFAULT NULL,
  "vi_employee_id" int NOT NULL,
  "vi_podatak_id" int DEFAULT NULL,
  "vi_vrsta_podatka" varchar(25) DEFAULT NULL,
  "vi_datetime" timestamp NOT NULL,
  PRIMARY KEY (vi_id)
);
CREATE INDEX IF NOT EXISTS "vi_kandidat_id" ON "idk_validnosti_inputa" (vi_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_viber_obavijesti" (
  "vo_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "vo_nalogid" int NOT NULL,
  "vo_kandidati_id" int NOT NULL,
  "vo_obavijest_za" varchar(255) NOT NULL,
  "vo_datetime" timestamp NOT NULL,
  PRIMARY KEY (vo_id)
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "phone" varchar(191) DEFAULT NULL,
  "name" varchar(191) NOT NULL,
  "nalog_id" int DEFAULT NULL,
  "email" varchar(191) NOT NULL,
  "password" varchar(191) NOT NULL,
  "kandidat_id" int NOT NULL,
  "last_online" timestamp DEFAULT NULL,
  "sim_id" varchar(255) DEFAULT NULL,
  "token" varchar(255) DEFAULT NULL,
  "type" varchar(15) DEFAULT NULL,
  "ne_viza" int DEFAULT NULL,
  "ne_srednja" int DEFAULT NULL,
  "ne_visoka" int DEFAULT NULL,
  "ne_dodatna" int DEFAULT NULL,
  "ne_iskustvo" int DEFAULT NULL,
  "ne_diploma" int DEFAULT NULL,
  "ne_pripravnicki" int DEFAULT NULL,
  "ne_strucni" int DEFAULT NULL,
  "ne_cert_jezik" int DEFAULT NULL,
  "ponovno_slanje" int DEFAULT NULL,
  "dipl_obavijest" int DEFAULT NULL,
  "notifikacije" int NOT NULL DEFAULT '0',
  "jezik" varchar(10) NOT NULL DEFAULT 'bs',
  "notf_new_year" int DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "users_email_unique" ON "users" (email);
CREATE INDEX IF NOT EXISTS "users_kandidat_id_unique" ON "users" (kandidat_id);

