-- Neon-Dev-Schema: 18 Kern-Tabellen aus dem MySQL-Produktions-Dump (26.02.2026) konvertiert
-- NICHT fuer Produktion - Foreign Keys bewusst weggelassen (Dev)

CREATE TABLE IF NOT EXISTS "idk_kandidati" (
  "kandidat_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kandidat_check" varchar(200) NOT NULL,
  "kandidat_ime" varchar(150) NOT NULL,
  "kandidat_prezime" varchar(150) NOT NULL,
  "kandidat_prijava_na" varchar(250) NOT NULL,
  "kandidat_spol" varchar(10) DEFAULT NULL,
  "kandidat_djevojackoprezime" varchar(150) DEFAULT NULL,
  "kandidat_jmbg" varchar(20) DEFAULT NULL,
  "kandidat_brojlk" varchar(50) DEFAULT NULL,
  "kandidat_broj_pasosa" varchar(50) DEFAULT NULL,
  "kandidat_datumrodjenja" date DEFAULT NULL,
  "kandidat_mjestorodjenja" varchar(150) DEFAULT NULL,
  "kandidat_drzavljanstvo_vrsta" varchar(100) DEFAULT NULL,
  "kandidat_drzavarodjenja" varchar(150) DEFAULT NULL,
  "kandidat_drzavljanstvo" varchar(150) DEFAULT NULL,
  "kandidat_bracnostanje" varchar(50) DEFAULT NULL,
  "kandidat_bracnostanjeod" date DEFAULT NULL,
  "kandidat_adresa" text,
  "kandidat_grad" varchar(150) DEFAULT NULL,
  "kandidat_pbroj" int DEFAULT NULL,
  "kandidat_drzava" varchar(150) DEFAULT NULL,
  "kandidat_email" varchar(250) DEFAULT NULL,
  "kandidat_mobitel" varchar(100) DEFAULT NULL,
  "kandidat_vozacka_dozvola" varchar(20) DEFAULT NULL,
  "kandidat_vozacka_kategorija" varchar(25) DEFAULT NULL,
  "kandidat_korisnickoime" varchar(250) DEFAULT NULL,
  "kandidat_password" varchar(150) DEFAULT NULL,
  "kandidat_slika" varchar(150) NOT NULL,
  "kandidat_status" int NOT NULL,
  "kandidat_status_messenger" int NOT NULL DEFAULT '0',
  "kandidat_datetime" timestamp NOT NULL,
  "kandidat_visitedurl" int DEFAULT '0',
  "kandidat_group" int NOT NULL DEFAULT '1',
  "kandidat_mailsent" int NOT NULL DEFAULT '0',
  "datum_termina" date DEFAULT NULL,
  "kandidat_bio_na_terminu" int DEFAULT NULL,
  "datum_aplikacije" date DEFAULT NULL,
  "kandidat_procjenatermina" int DEFAULT '0',
  "kandidat_viza" int DEFAULT NULL,
  "kandidat_viza_vrijedi_od" date DEFAULT NULL,
  "kandidat_viza_vrijedi_do" date DEFAULT NULL,
  "boravak_eu" varchar(255) DEFAULT NULL,
  "kandidat_status_prijave" int DEFAULT NULL,
  "kandidat_zaposlen_kod" int DEFAULT NULL,
  "cv_ba" int DEFAULT '0',
  "cv_de" int DEFAULT '0',
  "profile_ba" int NOT NULL DEFAULT '0',
  "profile_de" int NOT NULL DEFAULT '0',
  "kandidat_datum_ugovora" date DEFAULT NULL,
  "kandidat_datum_ugovora_mjesec" date DEFAULT NULL,
  "kandidat_datum_pocetakrada" date DEFAULT NULL,
  "kandidat_datum_pocetakrada_mjesec" date DEFAULT NULL,
  "kandidat_potencijalni_pocetak_rada" varchar(100) DEFAULT NULL,
  "kandidat_dogovoreni_pocetak_rada" date DEFAULT NULL,
  "kandidat_potvrden_pocetak_rada" int DEFAULT NULL,
  "kandidat_partnerid" int DEFAULT NULL,
  "kandidat_partner_status" int DEFAULT NULL,
  "kandidat_poslan_sms" varchar(255) DEFAULT NULL,
  "kandidat_sms_id" varchar(255) DEFAULT NULL,
  "kandidat_pogledao_link_prijave" int NOT NULL DEFAULT '0',
  "kandidat_poslan_dipl" int NOT NULL DEFAULT '0',
  "povezan_na_dipl" int NOT NULL DEFAULT '0',
  "kandidat_porijeklo" int NOT NULL DEFAULT '0',
  "struka_sa_prijave" int DEFAULT NULL,
  "kandidat_nalog_id" int DEFAULT NULL,
  "kandidat_latest_reserved_time" timestamp DEFAULT NULL,
  "kandidat_ppa_partner_id" int DEFAULT NULL,
  "kandidat_pp_lokacija" varchar(400) DEFAULT NULL,
  "kandidat_pp_pozicija" varchar(400) DEFAULT NULL,
  "kandidat_pp_plata" varchar(40) DEFAULT NULL,
  "kandidat_pp_povezao_user_id" int DEFAULT NULL,
  "kandidat_pp_razlog_odbijanja" varchar(255) DEFAULT NULL,
  "kandidat_pp_datum_prihvatanja" date DEFAULT NULL,
  "kandidat_dipl_id" int NOT NULL DEFAULT '0',
  "kandidat_ima_nostrifikaciju" int DEFAULT NULL,
  "kandidat_glossa" int NOT NULL DEFAULT '0',
  "kandidat_tf_status" int DEFAULT NULL,
  "kandidat_iskustvo_u_struci" int DEFAULT NULL,
  "kandidat_iskustvo_u_struci_trajanje" int DEFAULT NULL,
  "kandidat_termin_za_vizu" int DEFAULT NULL,
  "tf_reserved_agent" int DEFAULT NULL,
  "kandidat_nacin_odlaska" int NOT NULL DEFAULT '0',
  "kandidat_bracno_stanje" int NOT NULL DEFAULT '0',
  "kandidat_dostavljen_ugovor_jobstepu" int DEFAULT NULL,
  "kandidat_zeljena_regija" int DEFAULT NULL,
  "kandidat_zeljeni_grad" int DEFAULT NULL,
  "kandidat_partner_lead_status" int DEFAULT NULL,
  "zaduzeni_makler_id" int DEFAULT NULL,
  "zaduzen_makleru_datum" timestamp DEFAULT NULL,
  "zaduzeni_makler_reminder_datum" date DEFAULT NULL,
  "kandidat_nivo_obrazovanja" int DEFAULT NULL,
  "kandidat_partner_lead_biljeska" text,
  "kandidat_destinacija_grad" varchar(255) DEFAULT NULL,
  "kandidat_destinacija_postanski_broj" varchar(10) DEFAULT NULL,
  "assigned_to_makler" int DEFAULT NULL,
  "kandidat_paralelno_zb" int NOT NULL DEFAULT '0',
  "kandidat_pogresan_broj" int NOT NULL DEFAULT '0',
  "kandidat_nedostupan" int NOT NULL DEFAULT '0',
  "kandidat_atu_paket" int DEFAULT NULL,
  PRIMARY KEY (kandidat_id)
);
CREATE INDEX IF NOT EXISTS "kandidat_visitedurl" ON "idk_kandidati" (kandidat_visitedurl);
CREATE INDEX IF NOT EXISTS "kandidat_group" ON "idk_kandidati" (kandidat_group);
CREATE INDEX IF NOT EXISTS "kandidat_status" ON "idk_kandidati" (kandidat_status);
CREATE INDEX IF NOT EXISTS "kandidat_dipl_id" ON "idk_kandidati" (kandidat_dipl_id);
CREATE INDEX IF NOT EXISTS "kandidat_nalog_id" ON "idk_kandidati" (kandidat_nalog_id);
CREATE INDEX IF NOT EXISTS "tf_reserved_agent" ON "idk_kandidati" (tf_reserved_agent);
CREATE INDEX IF NOT EXISTS "kandidat_tf_status" ON "idk_kandidati" (kandidat_tf_status);
CREATE INDEX IF NOT EXISTS "kandidat_status_prijave" ON "idk_kandidati" (kandidat_status_prijave);

CREATE TABLE IF NOT EXISTS "idk_kandidat_jezici" (
  "kj_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kj_naziv" varchar(150) NOT NULL,
  "kj_naziv_de" varchar(255) DEFAULT NULL,
  "kj_slusanje" varchar(50) NOT NULL,
  "kj_slusanje_de" varchar(255) DEFAULT NULL,
  "kj_citanje" varchar(50) NOT NULL,
  "kj_citanje_de" varchar(255) DEFAULT NULL,
  "kj_govorna_interakcija" varchar(50) NOT NULL,
  "kj_govorna_interakcija_de" varchar(255) DEFAULT NULL,
  "kj_govorna_produkcija" varchar(50) NOT NULL,
  "kj_govorna_produkcija_de" varchar(255) DEFAULT NULL,
  "kj_pisanje" varchar(50) NOT NULL,
  "kj_pisanje_de" varchar(255) DEFAULT NULL,
  "kj_kandidatid" int NOT NULL,
  "kj_ustanova" int DEFAULT NULL,
  PRIMARY KEY (kj_id)
);
CREATE INDEX IF NOT EXISTS "kj_naziv" ON "idk_kandidat_jezici" (kj_naziv);
CREATE INDEX IF NOT EXISTS "kj_kandidatid" ON "idk_kandidat_jezici" (kj_kandidatid);
CREATE INDEX IF NOT EXISTS "kj_slusanje" ON "idk_kandidat_jezici" (kj_slusanje);

CREATE TABLE IF NOT EXISTS "idk_kandidat_radno_iskustvo" (
  "kri_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kri_order" int DEFAULT '0',
  "kri_darum_od" date NOT NULL,
  "kri_datum_do" date DEFAULT NULL,
  "kri_aktuelno" int NOT NULL DEFAULT '0',
  "kri_pozicija" varchar(250) NOT NULL,
  "kri_pozicija_de" varchar(400) DEFAULT NULL,
  "kri_pozicija_en" varchar(400) DEFAULT NULL,
  "kri_naziv" varchar(100) NOT NULL,
  "kri_naziv_de" varchar(250) DEFAULT NULL,
  "kri_grad" varchar(100) DEFAULT NULL,
  "kri_grad_de" varchar(200) DEFAULT NULL,
  "kri_drzava" varchar(100) DEFAULT NULL,
  "kri_adresa" varchar(100) DEFAULT NULL,
  "kri_telefon" varchar(50) DEFAULT NULL,
  "kri_email" varchar(50) DEFAULT NULL,
  "kri_web" varchar(50) DEFAULT NULL,
  "kri_opis" text,
  "kri_opis_de" text,
  "kri_kandidat_id" int NOT NULL,
  "kri_prikaz_pp" int NOT NULL DEFAULT '0',
  PRIMARY KEY (kri_id)
);
CREATE INDEX IF NOT EXISTS "kri_id" ON "idk_kandidat_radno_iskustvo" (kri_id);
CREATE INDEX IF NOT EXISTS "kri_kandidat_id" ON "idk_kandidat_radno_iskustvo" (kri_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_edukacija" (
  "ke_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ke_orderid" int NOT NULL DEFAULT '0',
  "ke_datumod" date DEFAULT NULL,
  "ke_datumdo" date DEFAULT NULL,
  "ke_aktuelno" int NOT NULL DEFAULT '0',
  "ke_smjer_id" int DEFAULT NULL,
  "ke_naziv_kvalifikacije" varchar(100) NOT NULL,
  "ke_naziv_kvalifikacije_de" varchar(100) DEFAULT NULL,
  "ke_skola_id" int DEFAULT NULL,
  "ke_naziv" varchar(100) DEFAULT NULL,
  "ke_naziv_de" varchar(250) DEFAULT NULL,
  "ke_grad" varchar(50) DEFAULT NULL,
  "ke_grad_de" varchar(200) DEFAULT NULL,
  "ke_drzava" varchar(100) DEFAULT NULL,
  "ke_opis" text,
  "ke_opis_de" text,
  "ke_kandidat_id" int NOT NULL,
  "ke_vrsta_obrazovanja" varchar(50) DEFAULT NULL,
  "ke_prikaz_pp" int NOT NULL DEFAULT '0',
  PRIMARY KEY (ke_id)
);
CREATE INDEX IF NOT EXISTS "ke_id" ON "idk_kandidat_edukacija" (ke_id);
CREATE INDEX IF NOT EXISTS "ke_kandidat_id" ON "idk_kandidat_edukacija" (ke_kandidat_id);

CREATE TABLE IF NOT EXISTS "idk_kandidati_grupe" (
  "kg_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kg_title" varchar(255) NOT NULL,
  "kg_title_de" varchar(255) DEFAULT NULL,
  "kg_title_it" varchar(255) DEFAULT NULL,
  "kg_date" timestamp NOT NULL,
  "kg_employeeid" int NOT NULL,
  "kg_status" int NOT NULL DEFAULT '1',
  PRIMARY KEY (kg_id)
);

CREATE TABLE IF NOT EXISTS "idk_kandidat_status" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_id" int DEFAULT NULL,
  "status_naziv" varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS "status_id" ON "idk_kandidat_status" (status_id);

CREATE TABLE IF NOT EXISTS "idk_kandidat_status_prijave" (
  "status_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "status_naziv" varchar(100) NOT NULL,
  "status_aktivan" int NOT NULL DEFAULT '0',
  "rezervisanje" int NOT NULL DEFAULT '0',
  "redoslijed_statusa" int DEFAULT NULL,
  PRIMARY KEY (status_id)
);

CREATE TABLE IF NOT EXISTS "idk_struke" (
  "id_struke" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "naziv_struke" varchar(255) NOT NULL,
  "naziv_struke_de" varchar(255) DEFAULT NULL,
  PRIMARY KEY (id_struke)
);

CREATE TABLE IF NOT EXISTS "idk_skole" (
  "skola_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "skola_naziv" varchar(255) NOT NULL,
  "skola_naziv_de" varchar(255) DEFAULT NULL,
  "skola_tip_obrazovanja" varchar(50) NOT NULL,
  PRIMARY KEY (skola_id)
);

CREATE TABLE IF NOT EXISTS "idk_skole_smjerovi" (
  "ss_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ss_naziv" varchar(255) NOT NULL,
  "ss_naziv_de" varchar(255) DEFAULT NULL,
  "ss_naziv_en" varchar(255) DEFAULT NULL,
  "ss_skola_id" int NOT NULL,
  "ss_trajanje_skole" int DEFAULT NULL,
  "ss_struka_id" int DEFAULT NULL,
  PRIMARY KEY (ss_id)
);

CREATE TABLE IF NOT EXISTS "idk_nd_kandidata" (
  "id_broj_nd_kandidata" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "ime_nd_kandidata" varchar(30) DEFAULT NULL,
  "prezime_nd_kandidata" varchar(50) DEFAULT NULL,
  "ulica_nd_kandidata" varchar(100) DEFAULT NULL,
  "postanski_broj_nd_kandidata" int DEFAULT NULL,
  "grad_nd_kandidata" varchar(100) DEFAULT NULL,
  "ulica_bor_nd_kandidata" varchar(100) DEFAULT NULL,
  "postanski_broj_bor_nd_kandidata" int DEFAULT NULL,
  "grad_bor_nd_kandidata" varchar(100) DEFAULT NULL,
  "mobilni_nd_kandidata" varchar(20) DEFAULT NULL,
  "email_nd_kandidata" varchar(50) DEFAULT NULL,
  "izdao_licnu_nd_kandidata" varchar(100) DEFAULT NULL,
  "jmbg_nd_kandidata" varchar(50) DEFAULT NULL,
  "broj_licne_karte_nd_kandidata" varchar(30) DEFAULT NULL,
  "skola_nd_kandidata" int DEFAULT NULL,
  "skola_smjer_nd_kandidata" int DEFAULT NULL,
  "poslodavac_nd_kandidata" int DEFAULT NULL,
  "poslodavac_nas_nd_kandidata" int DEFAULT NULL,
  "poslodavac_naziv_nas_nd_kandidata" int DEFAULT NULL,
  "poslodavac_naziv_nd_kandidata" varchar(200) DEFAULT NULL,
  "poslodavac_ulica_nd_kandidata" varchar(150) DEFAULT NULL,
  "poslodavac_postanski_broj_nd_kandidata" int DEFAULT NULL,
  "poslodavac_grad_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_regija_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_drzava_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_ime_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_prezime_nd_kandidata" varchar(50) DEFAULT NULL,
  "poslodavac_mail_nd_kandidata" varchar(100) DEFAULT NULL,
  "poslodavac_mobilni_nd_kandidata" varchar(50) DEFAULT NULL,
  "komentar_nd_kandidata" text,
  "vrijeme_kreiranja_nd_kandidata" timestamp DEFAULT NULL,
  "dodao_zaposlenik_nd_kandidata" int DEFAULT NULL,
  "zaduzen_zaposlenik_nd_kandidata" int DEFAULT NULL,
  "tim_nd_kandidata" int NOT NULL DEFAULT '0',
  "status_nd_kandidata" int DEFAULT NULL,
  "pstatus_nd_kandidata" int NOT NULL DEFAULT '1',
  "idd_ustanova_nd" int DEFAULT NULL,
  "broj_zahtjeva_na_ustanovi_nd_kandidata" varchar(100) DEFAULT NULL,
  "idd_kontakt_ustanova_nd" int DEFAULT NULL,
  "tracking_number_nd_kandidata" varchar(100) DEFAULT NULL,
  "link_tracking_number_nd_kandidata" int DEFAULT NULL,
  "vrsta_ugovora_nd_kandidata" int DEFAULT NULL,
  "rata1_nd_kandidata" int NOT NULL DEFAULT '0',
  "rata1_vrijeme_nd_kandidata" timestamp DEFAULT NULL,
  "rata2_nd_kandidata" int NOT NULL DEFAULT '0',
  "rata2_vrijeme_nd_kandidata" timestamp DEFAULT NULL,
  "povijest_nd_kandidata" int NOT NULL DEFAULT '0',
  "povijest_vrsta_nd_kandidata" int DEFAULT NULL,
  "kandidat_idd" int DEFAULT NULL,
  "partner_nd_status" int DEFAULT NULL,
  "kampanja_id" int DEFAULT NULL,
  "datum_rodjenja" date DEFAULT NULL,
  "in_vici_dial" int NOT NULL DEFAULT '0',
  "status_pp" int NOT NULL DEFAULT '3',
  "vrijeme_zakaznog_poziva" timestamp DEFAULT NULL,
  "status_zakaznog_poziva" int DEFAULT NULL,
  "zadnja_komunikacija" timestamp DEFAULT NULL,
  "chat_slike" text,
  "vrsta_obrade" int NOT NULL DEFAULT '0',
  "nivo_poznavanja_jezika" int NOT NULL DEFAULT '0',
  "certifikat_nd_kandidata" int NOT NULL DEFAULT '0',
  "inbound_aktivan" int NOT NULL DEFAULT '0',
  "poslan_spisak_datum" date DEFAULT NULL,
  "dokumentacija_kompletna_datum" date DEFAULT NULL,
  "na_prevodu_datum" date DEFAULT NULL,
  "prevod_zavrsen_datum" date DEFAULT NULL,
  "poslana_posta_datum" date DEFAULT NULL,
  "zaprimljena_dokumentacija_datum" date DEFAULT NULL,
  "stigla_taksa_dopuna_datum" date DEFAULT NULL,
  "placena_taksa_poslana_dopuna_datum" date DEFAULT NULL,
  "zavrsen_datum" date DEFAULT NULL,
  PRIMARY KEY (id_broj_nd_kandidata)
);
CREATE INDEX IF NOT EXISTS "kampanja_id" ON "idk_nd_kandidata" (kampanja_id);
CREATE INDEX IF NOT EXISTS "vrijeme_kreiranja_nd_kandidata" ON "idk_nd_kandidata" (vrijeme_kreiranja_nd_kandidata);
CREATE INDEX IF NOT EXISTS "status_nd_kandidata" ON "idk_nd_kandidata" (status_nd_kandidata);
CREATE INDEX IF NOT EXISTS "pstatus_nd_kandidata" ON "idk_nd_kandidata" (pstatus_nd_kandidata);
CREATE INDEX IF NOT EXISTS "povijest_nd_kandidata" ON "idk_nd_kandidata" (povijest_nd_kandidata);
CREATE INDEX IF NOT EXISTS "kandidat_idd" ON "idk_nd_kandidata" (kandidat_idd);

CREATE TABLE IF NOT EXISTS "idk_nostrifikovane_diplome" (
  "id_nd" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "id_cand_dipl" int DEFAULT NULL,
  "id_cand_job" int DEFAULT NULL,
  "file_nd" text NOT NULL,
  "upload_date_nd" timestamp DEFAULT NULL,
  "upload_employee_id" int DEFAULT NULL,
  "full_recognition" int DEFAULT NULL,
  PRIMARY KEY (id_nd)
);
CREATE INDEX IF NOT EXISTS "id_cand_dipl" ON "idk_nostrifikovane_diplome" (id_cand_dipl);
CREATE INDEX IF NOT EXISTS "id_cand_job" ON "idk_nostrifikovane_diplome" (id_cand_job);

CREATE TABLE IF NOT EXISTS "idk_link_generator" (
  "lg_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "lg_link_prijave" varchar(255) DEFAULT NULL,
  "idk_urlimg_prijave" varchar(500) DEFAULT NULL,
  "lg_url" varchar(255) NOT NULL,
  "lg_desc" varchar(255) NOT NULL,
  "lg_status" int NOT NULL DEFAULT '0',
  "lg_employeeid" int NOT NULL,
  "lg_datetime" timestamp NOT NULL,
  "lg_project" int DEFAULT NULL,
  "lg_nalogid" int DEFAULT NULL,
  "lg_language" varchar(20) DEFAULT 'bs',
  "lg_troskovi" double precision DEFAULT NULL,
  "lg_broj_pregleda" int NOT NULL DEFAULT '0',
  "lg_partner_app" int NOT NULL DEFAULT '0',
  PRIMARY KEY (lg_id)
);
CREATE INDEX IF NOT EXISTS "lg_nalogid" ON "idk_link_generator" (lg_nalogid);

CREATE TABLE IF NOT EXISTS "idk_nalozi" (
  "nalog_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "kompanija_id" int DEFAULT NULL,
  "employee_id" int DEFAULT NULL,
  "nalog_broj" varchar(255) DEFAULT NULL,
  "nalog_naziv" varchar(255) DEFAULT NULL,
  "nalog_opis" text,
  "nalog_kreirano" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "nalog_datum_potpisa_naloga" date DEFAULT NULL,
  "nalog_status" int DEFAULT NULL,
  "nalog_marketing_menadzer" int DEFAULT NULL,
  "nalog_ugovor" varchar(25) DEFAULT NULL,
  "nalog_potrebno_kandidata" int DEFAULT NULL,
  "nalog_provizija" double precision DEFAULT NULL,
  "nalog_provizija_po_plati" real DEFAULT NULL,
  "nalog_broj_rata" int DEFAULT NULL,
  "nalog_procenat_avansa" int DEFAULT NULL,
  "nalog_placa_nostrifikaciju" int NOT NULL DEFAULT '0',
  "nalog_nacin_nostrifikacije" int DEFAULT NULL,
  "nalog_provizija_nostrifikacija" double precision DEFAULT NULL,
  "nalog_broj_rata_nostrifikacija" int DEFAULT NULL,
  "nalog_firma_fakturisanja" int DEFAULT NULL,
  "nalog_placena_prva_rata" int NOT NULL DEFAULT '2',
  "nalog_financije" int NOT NULL DEFAULT '1',
  "nalog_akademija" int NOT NULL DEFAULT '0',
  "nalog_provizija_akademija" int DEFAULT NULL,
  "nalog_nacin_akademija" int DEFAULT NULL,
  "nalog_broj_dana_akademija" int DEFAULT NULL,
  "nalog_partner_active" int NOT NULL DEFAULT '0',
  "nalog_partner_provizija" double precision DEFAULT NULL,
  "pristup_poslodavcima" int NOT NULL DEFAULT '0',
  "partneri_pp" int NOT NULL DEFAULT '0',
  "nalog_prioritet" int DEFAULT NULL,
  "nalog_slanje_na_glosu" int NOT NULL DEFAULT '0',
  "nalog_dospijece" int NOT NULL DEFAULT '0',
  "nalog_smjerovi_kriterij" int NOT NULL DEFAULT '0',
  "nalog_js_partner_id" int DEFAULT NULL,
  "nalog_partner_app_title" varchar(255) DEFAULT NULL,
  "nalog_partner_app_location" varchar(255) DEFAULT NULL,
  "nalog_partner_app_until" timestamp DEFAULT NULL,
  "nalog_partner_app_salary" varchar(255) DEFAULT NULL,
  "nalog_poslodavac_trazi_jezik" int NOT NULL DEFAULT '0',
  "nalog_poslodavac_koristi_pp" int NOT NULL DEFAULT '0',
  "offers_and_benefits_of_employers" text,
  PRIMARY KEY (nalog_id)
);
CREATE INDEX IF NOT EXISTS "nalog_prioritet" ON "idk_nalozi" (nalog_prioritet);

CREATE TABLE IF NOT EXISTS "idk_notes" (
  "note_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "note_txt" text NOT NULL,
  "note_files" text,
  "note_datetime" timestamp NOT NULL,
  "note_group" int NOT NULL,
  "note_dataid" int NOT NULL,
  "note_employeeid" int NOT NULL,
  PRIMARY KEY (note_id)
);

CREATE TABLE IF NOT EXISTS "idk_timeline" (
  "timeline_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "timeline_type" int NOT NULL,
  "timeline_txt" text NOT NULL,
  "timeline_datetime" timestamp NOT NULL,
  "timeline_group" int NOT NULL,
  "timeline_dataid" int NOT NULL,
  "timeline_employeeid" int NOT NULL,
  PRIMARY KEY (timeline_id)
);

CREATE TABLE IF NOT EXISTS "idk_tasks" (
  "task_id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "task_txt" text NOT NULL,
  "task_replytxt" text NOT NULL,
  "task_duedatetime" timestamp NOT NULL,
  "task_assignedid" int NOT NULL,
  "task_emailnotifi" int NOT NULL,
  "task_repeatnotifi" int NOT NULL,
  "task_group" int NOT NULL,
  "task_dataid" int NOT NULL,
  "task_employeeid" int NOT NULL,
  "task_datetime" timestamp NOT NULL,
  "task_status" int NOT NULL,
  PRIMARY KEY (task_id)
);

